### ISSUE TITLE
fired grenades and rockets smoke effect slightly offset when facing East or West

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#1012]
They align perfectly when facing north/south, but when facing east/west the smoke look like they're off slightly to the side.

**Comment by TokyoSU** [comment]
Confirmed with Big gun rocket too, i suspect it's coming from the control of these projectiles.

**Comment by Lwmte** [comment]
Can you demonstrate the issue? I don't understand what you are both talking about.
