### ISSUE TITLE
Monkeyswing autograb also aligns Lara to nearest quadrant

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#1018]
Gian C. reported that using "Monkey auto-grab" feature (in settings.lua) also aligns player to nearest straight corner. Probably it happens because autograb shares code with ledge climb routine.

Additional report from Gian C.: "I did some testing and default direction seems to be East, unless there's a climbable wall in the room, in that case it screws up and Lara faces different directions."

**Comment by Sezzary** [comment]
Fixed.
