### ISSUE TITLE
Moveable:SetOnCollidedWithRoom (and possibly Moveable:SetOnCollidedWithObjects) do not work for lara

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1062]
For the room version, it doesnt work for lara but works for any other object.

fir the object version if lara is the second argument:

baddy = GetMoveableByName(“baddy”)
baddy:SetOnCollidedwithObject(collide)

LevelFuncs.collided(obj1, obj2)
      Print(“collided”)
end

then it works, but if lara is in the first argument:

Lara:SetOnCollidedWithObject(collided)

then it doesn’t work. But for any other object it does work.

**Comment by Kubsy** [comment]
![image](https://github.com/MontyTRC89/TombEngine/assets/80340234/6c08af6b-9274-45c6-b211-92cd19a04998)

**Comment by davidmarr** [comment]
I prepared a demo with 2 ANIMATINGs:
ANIMATING1 without collision box.
ANIMATING2 with collision box.
I used this code to set the function to be called
```
LevelFuncs.OnStart = function()
    LevelFuncs.__SetCollisionWithLaser()
    LevelFuncs.__SetCollisionWithLaserBox()
end
LevelFuncs.__SetCollisionWithLaser = function()
    local lasers = GetMoveablesBySlot(ObjID.ANIMATING1)
    for _, laser in pairs(lasers) do
        laser:SetOnCollidedWithObject(LevelFuncs.__DoLaserKill)
        print(laser:GetName())
    end
end
LevelFuncs.__SetCollisionWithLaserBox = function()
    local lasers = GetMoveablesBySlot(ObjID.ANIMATING2)
    for _, laser in pairs(lasers) do
        laser:SetOnCollidedWithObject(LevelFuncs.__DoLaserKill)
        print(laser:GetName())
    end
end
LevelFuncs.__DoLaserKill  = function(obj1, obj2)
    print(obj1:GetName() .. " collided with " .. obj2:GetName())
    obj2:SetEffect(EffectID.SPARKS)
    obj2:SetHP(0)
end
```
Without collision box the function is called almost all the time. In some angles the function is not called.
With the collision box calculated the function is called rarely, despite Lara being in collision with the animating


https://github.com/MontyTRC89/TombEngine/assets/116632612/1c7b2d9e-7392-4a69-82ca-c8800daa6507


https://github.com/MontyTRC89/TombEngine/assets/116632612/bd47ecac-f4ea-4070-9926-6a90b26260f7


https://github.com/MontyTRC89/TombEngine/assets/116632612/7b839c5a-7712-45c9-acc3-b8f85e143060

I leave the test level to do further testing and investigation
[Link test level](https://mega.nz/file/OsEAmSJS#v447GGnURTRtY3R8-U8Lqka_0V7gFtvwclseWER758k)
