### ISSUE TITLE
Lara's Meshes Explode When Shooting A Smash_Object

### ISSUE THREAD

**Issue by ShadowXJaw724** [MontyTRC89/TombEngine#1073]
If you use a Harpoon gun to shoot a smash object, instead of the mesh, it explodes the mesh of Lara but without actually killing her. It also seems to mess up everything, but im not sure about that one.

**Comment by Stranger1992** [comment]
**Please ensure you provide a WAD2 , project file and full explanation of what the bug is, how it happened and what steps are needed to recreate it**
