### ISSUE TITLE
When pushing action in front of puzzle/key holes, inventory appears for 1 frame and disappears

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#1083]
I believe this issue is related to some control system changes which send action key to an inventory even if it was already pressed by the time game enters into inventory loop. I remember solving this issue. It requires this: you must not register key input which was already held by the time game enters into inventory loop, and only after user releases the key and pushes it again.

**Comment by Sezzary** [comment]
Fixed.
