### ISSUE TITLE
Knife thrower not work correctly.

### ISSUE THREAD

**Issue by Vasatomb** [MontyTRC89/TombEngine#1099]
https://user-images.githubusercontent.com/129717002/236415750-aba3259f-4b52-4c8b-af34-8d5be5a4503c.mp4

**Comment by Stranger1992** [comment]
Please provide a test project, and wad2 and an explanation of what this issue is. Until then, this issue will be closed.

**Comment by Vasatomb** [comment]
in the video: a knife thrower can suddenly take and run into a wall and that's it... so it butts the wall.
