### ISSUE TITLE
Bridge tilt does not work at certain directions

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1101]
apparently the tilts do not work at certain directions:

![IMG_0359](https://user-images.githubusercontent.com/80340234/236499042-79c2024e-668d-416e-88d3-261d45487c1e.jpeg)
![IMG_0360](https://user-images.githubusercontent.com/80340234/236499057-2af6c49b-0172-4044-82f5-10a3a6cd9caf.jpeg)
![IMG_0361](https://user-images.githubusercontent.com/80340234/236499064-f737ba54-aff5-4000-a956-3d7be3ab0ebb.jpeg)

**Comment by Lwmte** [comment]
Fixed
