### ISSUE TITLE
Classic Rolling ball bug

### ISSUE THREAD

**Issue by Vasatomb** [MontyTRC89/TombEngine#1108]
rolling ball resting against an object (a door, a moving block, and even another rolling ball) continues to move in place indefinitely.

https://github.com/MontyTRC89/TombEngine/assets/129717002/7997b9ee-346c-4a65-be2c-a98035884061

**Comment by Lwmte** [comment]
Test level, please.

**Comment by Stranger1992** [comment]
@Vasatomb please provide a test level , with all the WAD2 files you are using , any LUA scripts in use and this issue will be looked into further.

**Comment by Vasatomb** [comment]
> @Vasatomb please provide a test level , with all the WAD2 files you are using , any LUA scripts in use and this issue will be looked into further.



> 



> Test level, please.

https://dropmefiles.com/QY0Px

**Comment by Lwmte** [comment]
Fixed
