### ISSUE TITLE
Zipline handle bugs

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#1121]
- [x] Zipline works on one cardinal point (north) whilst on others it doesn't.
- [x] Lara can only interact with the zipline when he drops and pulls herself up from ledge to the same tile. Then she can grab it. 

https://github.com/MontyTRC89/TombEngine/assets/80340234/d2991fd3-84a2-453f-942b-9354a0f52fd6

**Comment by Lwmte** [comment]
Possibly fixed in f2cab33e2ff4fcab225cc950881939ea3aae4e66
