### ISSUE TITLE
Wrong sun light direction/orientation on dynamic objects

### ISSUE THREAD

**Issue by raymi6** [MontyTRC89/TombEngine#1143]
Objects with dynamic lighting don't have a correct light direction from suns applied to them

Sun pointing north : Lara receives Light from south west direction
![Capture d'écran 2023-06-18 122018](https://github.com/MontyTRC89/TombEngine/assets/9752185/fa1f6527-6a96-47e2-8b29-869fa2a73c95)
![Capture d'écran 2023-06-18 122124](https://github.com/MontyTRC89/TombEngine/assets/9752185/82045df4-5bc9-4a69-8b76-2eee01780860)
![Capture d'écran 2023-06-18 122142](https://github.com/MontyTRC89/TombEngine/assets/9752185/6fc9a546-505e-46fe-8886-0e9738a52265)

Sun pointing south : Lara receives light from south west direction
![Capture d'écran 2023-06-18 122518](https://github.com/MontyTRC89/TombEngine/assets/9752185/79bb31d2-7241-407c-af6e-ff302c646e26)
![Capture d'écran 2023-06-18 122453](https://github.com/MontyTRC89/TombEngine/assets/9752185/3da822d4-cae1-4640-bcfc-23df37b3d132)

Sun pointing west : Lara receives Light from south west
![Capture d'écran 2023-06-18 122843](https://github.com/MontyTRC89/TombEngine/assets/9752185/c482f631-08c4-4fed-92d2-fcc74fd84ab9)
![Capture d'écran 2023-06-18 122724](https://github.com/MontyTRC89/TombEngine/assets/9752185/d1a60d08-15ea-4393-8634-c9838026aacf)

Sun pointing east : Lara receives light from south west
![Capture d'écran 2023-06-18 123104](https://github.com/MontyTRC89/TombEngine/assets/9752185/51b09c08-668b-46f1-93e4-6d564772dcff)
![Capture d'écran 2023-06-18 123023](https://github.com/MontyTRC89/TombEngine/assets/9752185/a77e3380-437e-4a0e-b0d4-e4fca3cd2eb7)

**Comment by Kubsy** [comment]
solved on develop_renderer
