### ISSUE TITLE
Torch No Longer Has Flame Sprite when Lit (TEN 1.1.0)

### ISSUE THREAD

**Issue by ses9134** [MontyTRC89/TombEngine#1173]
Torch No Longer Has Flame Sprite when Lit. With TEN 1.1.0

![image](https://github.com/MontyTRC89/TombEngine/assets/33204891/6c30c257-073f-4af4-a880-a090a04718da)

**Comment by Lwmte** [comment]
Builder did not update shader files along with 1.1.0 binaries.
