### ISSUE TITLE
Game crashes to desktop when Lara wades in water

### ISSUE THREAD

**Issue by richardba** [MontyTRC89/TombEngine#1184]
Level is attached bellow, 

Basically, when Lara goes into water, then goes to surface and starts to wade. Game crashes to desktop. The same behavior is also seen into Dozy mode, but the water one is more worrisome  

[Level.zip](https://github.com/MontyTRC89/TombEngine/files/12318986/Level.zip)

**Comment by Sezzary** [comment]
Sorted. For future reference of anyone checking this issue: all names of hair bones must be unique.

**Comment by richardba** [comment]
Addendum: The root cause of the issue is, when the hair object has several meshes with the same name, the game crashes.
