### ISSUE TITLE
Search Object 4 (box case) displays wrong meshes

### ISSUE THREAD

**Issue by Gancian** [MontyTRC89/TombEngine#1188]
By TRC default, when using the SEARCH_OBJECT4 item, the game should display in-game only its meshes 0, 1 and 3 during normal gameplay and only its meshes 2, 4 and 5 when activating the x-ray machine.
In TombEngine, only meshes 0 and 3 are visible in normal gameplay, rendering the inside of the box (mesh 1) invisible.

**Comment by Gancian** [comment]
![image](https://github.com/MontyTRC89/TombEngine/assets/30839164/c11c98c4-10f8-4619-9aab-418bfcf68909)

screenshot taken with Tomb Engine 1.1.0 and original SEARCH_OBJECT4 ripped from RICH2.TRC

**Comment by Kubsy** [comment]
This should be done via lua
