### ISSUE TITLE
Trapdoor blocks the monkeyswing flag on the same sector

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#1195]
![image](https://github.com/MontyTRC89/TombEngine/assets/80340234/64e369c8-13bb-438b-8bc1-c0a4d3e84ce5)

As shown on the screenshot - I have 4 stacked room with 1 sector having a trapdoor and a monkeyswing flag, unfortunately lara refuses to proceed and feels like the trapdoor is blocking or rather overriding the monkeyswing flag which makes nonexisting

**Comment by Lwmte** [comment]
Does it happen in tomb4? If so, I think it's original floordata issue which may be also treated as a "feature", so I doubt it needs fixing.

**Comment by Adngel** [comment]
Is this a duplicated issue? 

https://github.com/MontyTRC89/TombEngine/issues/681

**Comment by Lwmte** [comment]
Yes, it is. Closing.
