### ISSUE TITLE
Feature Request - Imported Geometry: Option to use Vertex Colors and Calculate from Room Lights together.

### ISSUE THREAD

**Issue by FeralPotato** [MontyTRC89/TombEngine#1198]
The option to have imported geometry be affected by static room lights while still showing their vertex colors would allow builders to add ambient occlusion, edge highlights and other details to imported geometry.

![VC](https://github.com/MontyTRC89/TombEngine/assets/142438849/a30333b9-31d3-4d13-8736-bbf04513edc0)
To illustrate what I mean, a balcony model with vertex color ambient occlusion and without.

**Comment by Lwmte** [comment]
Wrong repository. Ask in https://github.com/MontyTRC89/Tomb-Editor/issues
