### ISSUE TITLE
Voice audio track is not affected by any volume sliders

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#1201]
Even when both music and sound were set to really low the voice track is still at maximum volume. Perhaps linking this to sound's volume setting would help?

**Comment by GeckoKid-JW** [comment]
Further tests show that it is working, but only for any future voice tracks that will play - ie the sliders don't affect the voice track that is currently playing.

**Comment by Lwmte** [comment]
Fixed in ce447f3d0b3cc949adc7470909cfe7a85a467db2
