### ISSUE TITLE
Update TEN Wad for version: TEN 1.1.1

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/TombEngine#1205]
Hi, for the next TEN version I think we should update some things in the TEN Wad, I'll make this list to show the changes more explicitely.

Basically 4 tasks:
1. Add animations for the new pushables version.
2. Remove the switch sounds from Lara, to promote the switch sounds on switch objects.
3. Fix the bugs in the TRex and Yeti kill animations.
4. Polish consistency.

### LARA
- [x] Added PUSHABLE_BLOCK_PULL on slot 343.
- [x] Added PUSHABLE_BLOCK_PUSH on slot 345.
- [x] Added PUSHABLE_OBJECT_PUSH_EDGE_SLIP on slot 364.
- [x] Added PUSHABLE_BLOCK_PUSH_EDGE_SLIP on slot 366.
- [x] Remove switch sound on WALLSWITCH_DOWN (63).
- [x] Remove switch sound on WALLSWITCH_UP (64).
- [x] Remove switch sound on UNDERWATER_SWITCH (129).
- [x] Remove switch sound on SWITCH_SMALL_DOWN (195).
- [x] Remove switch sound on SWITCH_SMALL_UP (196).
- [x] Remove switch sound on BUTTON_PUSH (197).
- [x] Remove switch sound on HOLE_GRAB (325).
- [x] Remove switch sound on BIG_BUTTON_PUSH (413).
- [x] Remove switch sound on VALVE_TURN (470).
- [x] MontyTRC89/Tomb-Editor#718

### LARA_EXTRA_ANIMS
- [x] Change name to animation "UNSURE?" (0)  for "DAGGER_PICKUP"
- [x] Change name to animation "UNSURE?" (5)  for "SHARK_DEATH"
- [x] Change name to animation "DEATH_SETH" (14)  for "SETH_DEATH" (For consistency with similar situations)
- [x] Change values in UNSURE? (0).: Next Anim -> 0, Next frame -> 0 (For consistency with similar situations)
- [x] Change values in TYRANNOSAUR_DEATH (4).: Next Anim -> 4, Next frame -> 76
- [x] Add YETI_DEATH animation from TR2 levels.
- [x] Change values in YETI_DEATH (15). : Next Anim -> 15
- [x] Move DEATH_BIG_SCORPION (442) From ID_LARA onto ID_LARA_EXTRA_ANIMS

Resources:
Wad with Pushable animations: https://drive.google.com/file/d/148beIwuSpyUXaPc0vBzkYU9i_v1t0jSi/view?usp=sharing

**Comment by Stranger1992** [comment]
#Update animation names of LARA_EXTRA_ANIM (TEN)

**Comment by Stranger1992** [comment]
All issues fixed 👯

**Comment by Adngel** [comment]
2.1 version launched. Closing issue.
