### ISSUE TITLE
Savegame numbers resets every time the game is launched

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#1214]
Savegames start at 001 each time the game exe is launched, it works fine and increments if the level is returned to title and restarted via New Game.

**Comment by GeckoKid-JW** [comment]
scenario:
launch game -> new game -> save game, it increments from 001 to 002 to 003 etc.
exit to title -> new game -> save game, it saves to 004 -> load game 001 -> save game again, now the savegame is numbered 002, when it should be 005. loading 002 now and saving game and the next save will be 003 instead of 006.

this scenario acts similar when quitting the game entirely and relaunching:
scenario 2:
- there are already multiple savegames in the game
launch game -> new game -> save game restarts at 001.
this is not consistent with scenario 1 when saving a new game where it would add to the previous savegame number.

real life scenario 3:
- saving a new save game during gameplay up to 051 (for example), but realising this savegame is not good (lara's gonna die etc) so they load up 050 which is at an earlier point. They save the game again from 050 to another slot that 051 was not. Now they died again, and press load game: there are now TWO 051 savegames in the savegame list. 
This occurred during a twitch playthrough during a timed run.

proposal: just increase the latest savegame number regardless of new game or not.

**Comment by Lwmte** [comment]
Fixed
