### ISSUE TITLE
Diagonal Wall and Ghost Block above = Lara is going through when she rolls toward the wall

### ISSUE THREAD

**Issue by Christian-Croft** [MontyTRC89/TombEngine#1234]
https://github.com/MontyTRC89/TombEngine/assets/145125826/393983eb-6342-4e48-b3b2-ca0023592618

When performing a roll, Lara is clipping through the diagonal wall. On the room above, on the same floor coordinate there is a ghost block. It seems that it does not occur when the wall are straight.

This happens for all four directions.

Here a screenshot of the setup
<img width="229" alt="Capture d’écran 2023-10-18 à 22 38 19" src="https://github.com/MontyTRC89/TombEngine/assets/145125826/b0f746e2-9cef-4f40-af61-5d3114d612be">

a PRJ to test: 
[DiagWallGhostBlock.zip](https://github.com/MontyTRC89/TombEngine/files/13033763/DiagWallGhostBlock.zip)

**Comment by Christian-Croft** [comment]
Lara is also clipping and going on the upper room if she jumps and grab toward the diagonal wall

**Comment by Lwmte** [comment]
TE floordata compiler bug. Fixed.
