### ISSUE TITLE
Bug related to 2 click sectors

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/TombEngine#1268]
In the current state of develop branch (20/11/2023) I've found acouple of issues.

- When Lara is over a triangle sector that has a lean of 2 clicks, she slides throught it. It was expected that she do not slope because it was 2 click.
   - She doesn't slide on the normal 2 click tiles,
   - She doesn't slide on the 1 click triangles.

![Sliding](https://github.com/MontyTRC89/TombEngine/assets/60930991/691bdaf1-8cb6-46d6-8408-f7d0c2d885a7)

![Sliding2](https://github.com/MontyTRC89/TombEngine/assets/60930991/c49308ba-b20c-48c4-9358-b69cf4b5574e)

- When Lara is trying to climb at a surface accross a vertical portal. (to a higher room), there are several circunstances when she fails.

Example 1: Climbing of 4 clicks from a 2 slope floor, she doesn't start the jump.
![slopes2](https://github.com/MontyTRC89/TombEngine/assets/60930991/8fe3e68d-0734-4c8f-9379-877cb0cdcd2f)

Example 2: Climbing of 6 or 7 clicks to grab a floor at a higher room, she does the jump but she pass to shimming and end grabbing the wall, she can't move upr, left nor right, just drop.
![Climbing](https://github.com/MontyTRC89/TombEngine/assets/60930991/e0da4073-4eb3-4ed0-88d2-5531c1eaa1c3)
![Climbing2](https://github.com/MontyTRC89/TombEngine/assets/60930991/d6f1bef1-639e-493d-98aa-ec6dca347e01)

Both actions are currently possible in the version 1.2 (master branch). But these bugs are performing in the current develop branch.

**Comment by Sezzary** [comment]
Temporarily reverted a commit while I search for the cause.
