### ISSUE TITLE
Activating Teeth Spikes generates a warning in the log

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/TombEngine#1303]
When Teeth Spikes trap is activated, it generates the next type of warning.

[2023-Dec-28 14:28:36] [warning] Attempted to fetch LaraInfo data from entity with object ID 341

Object ID 341 is the Teeth Spikes.

Tracking the issue with debug mode:

- The printed line is from lara_helpers.cpp line 1218.  Is what happens in the function GetLaraInfo when the item is not Lara (like this case, this function is being activated with the TeethSpike as item).
- That function was called from collide_item.cpp line 1801, Function DoObjectCollision
- And the function DoObjectCollision is called from tr4_teethspike.cpp line 52, the function DoTeethSpikeCollision.

I have not experienced any other problem beyond the log warning, but I open this issue for it can be reviewed.

**Comment by Lwmte** [comment]
It seems to be there was a stray line which did nothing but tried to get Lara info from *any* object which is trying to calculate its collision against other object. I have now removed it.
