### ISSUE TITLE
Teleport and rooms

### ISSUE THREAD

**Issue by LGG-PRODUCTION** [MontyTRC89/TombEngine#1304]
I've seen that the teleport works, but the teleporter and the trigger must be in the same room, or Lara will get stuck..

https://github.com/MontyTRC89/TombEngine/assets/58694282/5cde2a03-7b4b-47d3-873a-a7ac377acd8d

**Comment by Lwmte** [comment]
Can't reproduce this issue. Please provide test project (not .ten file, but .wad2 + .prj2 + texture files).

**Comment by Jakub768** [comment]
As LWmte said, please reopen the issue with necessary test project.
