### ISSUE TITLE
Pistols get harmless after using DOZY

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/TombEngine#1309]
In develop branch (03/ January / 2024) when I use DOZY, the pistols stops causing damage to enemies. . Even if I go to the title menu and back to the level. The only way to restore the pistols damage is closing the game and opening again. This do not happens with the other weapons, only with the pistols.

**Comment by Lwmte** [comment]
Can't reproduce, need precise steps to reproduce it and test level.

**Comment by Adngel** [comment]
Can't reproduce bug anymore. I guess it was quietly fixed at some point.

Closing issue.
