### ISSUE TITLE
Bug: Little Beetles don't get rendered

### ISSUE THREAD

**Issue by FeralPotato** [MontyTRC89/TombEngine#1323]
The Little Beetles drain Lara's health when activated, but they stay invisible.

**Comment by FeralPotato** [comment]
Update on this bug - the little beetles suddenly pop into existence when Lara shoots any weapon.
https://discord.com/channels/1072511394735464498/1073914803711660112/1200938335045177388

**Comment by Adngel** [comment]
It happens also in my level, however I can't test for long because the game get crashed short after trigger the bettles.

**Comment by Stranger1992** [comment]
This bug (literally) does not exist on the current `develop` branch . However there is a silent crash that is happening with the `ID_LITTLE_BEETLES` that is unrelated to this issue. I will close this issue as it has been fixed and open a new one for the crash.
