### ISSUE TITLE
Use mesh offsets from LARA_SKIN instead of LARA

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/TombEngine#1354]
The **LARA** object is used for:
- Lara's **animations**
- Lara's **meshes offsets** (their positions relative to one another)

The **LARA_SKIN** object is used for:
- Lara's meshes appearance

_This is fine with 90% of the available outfits._

However: **some outfits change these mesh offsets**, usually to give Lara more realistic proportions.
Examples of this are:
- Mrshina's AOD outfit: https://github.com/Joey79100/trle-aod_animations/tree/master/Assets/Objects
- THOR2010's Legend and Anniversary ports: https://www.trsearch.org/item/5960 & https://www.trsearch.org/item/5876
- Vandersweater's "Lara's Tennis Outfit": https://www.aspidetr.com/minisites/easter24/day02/

-----------------

This is a problem when using custom animations, or when TEN Lara's animations are updated:
- The outfit maker HAS to copy their edits from LARA_SKIN to LARA
- The builder HAS to replace/edit their LARA object
The _**workaround**_ for this, is to use the edited LARA object, and import all the custom / TEN Lara animations over it in WadTool.
But this takes time, and doesn't allow quick testing of Lara's outfits.

If the builder doesn't do those steps, this is what they get:
![distLara1](https://github.com/MontyTRC89/TombEngine/assets/12445716/fe3e9c93-cc2a-4ee3-a232-1ae7ff2e9672)
![distLara2](https://github.com/MontyTRC89/TombEngine/assets/12445716/f00648eb-029f-48c3-be06-daa369520520) ![distLara3](https://github.com/MontyTRC89/TombEngine/assets/12445716/c467c6e2-e3de-4b80-967a-2917ada2cf1a) ![distLara4](https://github.com/MontyTRC89/TombEngine/assets/12445716/835b282c-4041-4709-a32a-bfdec0470092)
_(images are courtesy of LoreRaider)_

-----------------

To make like easier on builders and outfit makers, TEN should reference Lara's meshes offsets **not from the LARA** object, but **from the LARA_SKIN** object.
For classic outfits, there should be 0 visible difference.
For outfit makers, this will allow them to edit Lara's proportions without making the using their outfit more tedious.

_Note: Tomb Editor and WadTool already render LARA using LARA_SKIN position, so it looks fine there. It's only in-game that it doesn't behave in a "logical way"._

**Comment by Lwmte** [comment]
It will be easier to copy mesh offsets from LARA_SKIN to LARA on TE side when building a level.

**Comment by Lwmte** [comment]
Fixed on TE side.
