### ISSUE TITLE
transparencies do not update during alpha test animated texture sequences

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#1363]
as title, the transparent bits do not update with the animated texture when it is in alpha testing (magenta texture), showing through the horizon behind it. This is a regression as it used to work before.

with closer study it seems like the transparency throughout the sequence carry through but the first frame appear to be "stencilled" through and appear static.

https://github.com/MontyTRC89/TombEngine/assets/111427436/b1eb4f2a-15c3-470a-8ee8-962a1a7e148e

**Comment by Stranger1992** [comment]
@GeckoKid-JW is this issue with the 60FPS build? I think it was fixed?

**Comment by Stranger1992** [comment]
Fixed #1365
