### ISSUE TITLE
[ Feature Request ] Implement getters for Flow.Fog

### ISSUE THREAD

**Issue by Stranger1992** [MontyTRC89/TombEngine#1367]
### Is your feature request related to a problem? Please describe.

Currently, you can only SET the fog colour and distance but not get it. 

### Describe the solution you'd like

In order to implement changing fog properties so that they are carried over when the game saves and loads: I need the Lua API to be extended to allow for this.

### Describe alternatives you've considered

There are mentions of getting the fog properties in the code but its not finished as far as I can tell.

### Additional context

n/a

**Comment by davidmarr** [comment]
you can get the values directly from the object. 
Try this code:
```lua
local level = TEN.Flow.GetCurrentLevel()
print(tostring(level.fog.color))
print(tostring(level.fog.minDistance))
print(tostring(level.fog.maxDistance)) 
```

**Comment by Jakub768** [comment]
As david said, you can already do that with GetCurrentLevel(). For nodes, you can just have a variable with getting the level then implement a getter node which gets these values.
