### ISSUE TITLE
[ Feature Request ] Implement a getter to get the current level time (from statistics)

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1368]
### Is your feature request related to a problem? Please describe.

There is currently no way to check the current level time (assuming we check the timer from statistics) this is crucial if one wants to implement TR1-3 level end (it is possible by keeping track of bullets shot, medis used via lua levelvars) or do some other events with it.

### Describe the solution you'd like

A solution would be to implement a getter in Lua API which returns the timer in HH::MM::SS format (so basically in statistics screen)

### Describe alternatives you've considered

I guess you could manually do that in Lua but I am not sure if it works.

### Additional context

n/a

**Comment by Lwmte** [comment]
Implemented in #1495
