### ISSUE TITLE
[BUG REPORT] Moving Briges Jumping collision

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/TombEngine#1370]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

When Lara jumps over bridges platforms on movement, she collides with an invisible shape what makes her landing at the edge of the platform, or failing the jumps. In some cases she also gets teleported under the platform.

### To Reproduce

Create a bridge object (bridge, trapdoor, twoblock_Platform, etc...) and move it continously with lua code, while the platform is on movement, Lara will have problems jumping over it. (.ten file and lua code provided ahead).

Error happened in develop branch (17/05/2024) not in the TEN 1.4 version.

### Expected Behaviour

Expected behaviour, Lara can jump over platforms in current TEN version: https://streamable.com/hr8utd

### Screenshots

Video with the jumping issues in 60 fps branch: https://streamable.com/9lmsli

### Additional Content

Error happened in develop branch also in the 60 fps branch. (17/05/2024)

### Minimal reproduction project

Zip with the level.ten and the level lua script that contains the movement functions.
Google Drives: https://drive.google.com/file/d/1w5VYI8T6ohpxfHjjChEIJ4SPpuLb7Wzv/view?usp=sharing (39 MB)

**Comment by Jakub768** [comment]
Fixed just now by Sezz
