### ISSUE TITLE
[ Bug Report ] Bug in the path for the SetIntroImagePath() function.

### ISSUE THREAD

**Issue by davidmarr** [MontyTRC89/TombEngine#1371]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

The Flow.SetIntroImagePath() function looks for the image inside the `Engine\Bin\x64` (or x86 depending on the operating system) folder. 

### To Reproduce

The path `Flow.SetIntroImagePath("Screens\main.jpg")` returns a warning. 
The path `Flow.SetIntroImagePath("..//..//Screens\main.jpg")` works correctly

### Expected Behaviour

the `SetIntroImagePath` function should look for images directly in the Screens folder

### Screenshots

![image](https://github.com/MontyTRC89/TombEngine/assets/116632612/913c3919-6248-4b9d-bdec-f0b68977f309)

### Minimal reproduction project

files for testing are located in the base project when it's created with TIDE

**Comment by Lwmte** [comment]
Fixed
