### ISSUE TITLE
[ Feature Request ] Default to Load Game if Lara died and game overed instead of New Game

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#1373]
### Is your feature request related to a problem? Please describe.

Been watching a few streams and they have been accidentally started a new game after they have died a few too many times, and got stuck with a long starting flyby from a new game. Some stream comments are saying it's "one of the most annoying thing ever"

### Describe the solution you'd like

Either change the default to hover over Load Game, or the actual load savegame menu if they were launched to the title screen by having the level ended by dying.

**Comment by Lwmte** [comment]
Implemented in 1.5
