### ISSUE TITLE
[ Bug Report ] Burning torch's flame remains active on Lara's hand until the end of the throwing animation

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/TombEngine#1376]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

# Context
While holding a torch:
- Lara's left hand is swapped to a version of her hand that holds the torch (from the `LARA_TORCH_ANIM` slot).
- If the torch is burning, a small flame appears.  
  It is attached to Lara's hand, but its position is offset so it appears on the torch.

When **throwing the torch**:
- Lara's animation 1 from the `LARA_TORCH_ANIM` slot is played (just her left arm).
- An actual torch object is spawned in the middle of the animation (to initiate the actual "throwing physics").
- Lara's hand is swapped back to its regular version.

# The bug
1. The flame that is attached to _Lara's hand_ remains active until the entire throw animation is finished.
2. The flame on the actual torch seems to appear 2 frames late, rather than instantly.

_This was already happening in TRNG, so probably in TR4 and TR5 as well._

### To Reproduce

Pickup a torch, find a flame to make it burn, and throw it using the Draw key.

### Expected Behaviour

The flame that is attached to Lara's hand should disappear as soon as the actual torch is spawned / her hand is swapped back to its regular version.

### Screenshots

See this slow-motion video to see the issue in detail:
https://github.com/MontyTRC89/TombEngine/assets/12445716/bf372fed-051a-4043-bd2a-5c8ca56c9319

And just in case, a pic describing the issue:
![image](https://github.com/MontyTRC89/TombEngine/assets/12445716/d55bac5d-0ec1-454f-b53b-58791702cd8e)

### Minimal reproduction project

When you start the level, there's a torch top pickup + a non-lethal flame right in front of you.

https://drive.google.com/file/d/1O-j7QmbjoI1aVpWDPHlZUbg7ImhIEcqv/view?usp=sharing

**Comment by Adngel** [comment]
Bug fixed and pushed to develop branch.

Commit: https://github.com/MontyTRC89/TombEngine/commit/1f4404d76010c74e76bdcdccd593037c9c27975c

**Comment by Jakub768** [comment]
Fixed in this commit: https://github.com/MontyTRC89/TombEngine/commit/1f4404d76010c74e76bdcdccd593037c9c27975c
