### ISSUE TITLE
[ bug Report ] Water foot steps do not work for water rooms height below 0.75 click.

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#1383]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

The water rooms of half or quarter height do not have water footstep sounds.

### To Reproduce

Create a water room of 0.5 click or 0.25 click. Run Lara through it.. There will be no water footstep sounds.

### Expected Behaviour

I expected to hear the water footsteps. It works fine for 0.75 click height.

### Screenshots

![waterSnd](https://github.com/MontyTRC89/TombEngine/assets/120750885/e2d9380d-ca0e-4fea-b38b-8c20ca94db53)

### Minimal reproduction project

D

**Comment by Sezzary** [comment]
Fixed.
