### ISSUE TITLE
[ bug Report ] Lara refused to get out of water in a specific setup

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#1387]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

Lara is refusing to get out of water room with a single click block. I tried making a new project to reproduce the issue and the issue was still present.

### To Reproduce

Have one click dry room between the rooms and in the bottom room have no walls where Lara should get out.

Jump in water and make Lara get out of any of the side rooms. She will not get out.

### Expected Behaviour

Lara should get out of water.

### Screenshots

Attached video.

https://www.youtube.com/watch?v=aK-iF3i65sw

### Minimal reproduction project

https://discord.com/channels/1072511394735464498/1073914803711660112/1265115200730824806

Uses Cattext

**Comment by Sezzary** [comment]
Should be fixed for 1.5.
