### ISSUE TITLE
Butler disregards collision from objects

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#1390]
If you use the butler, it goes through all objects, thus ignoring collisions. 
Of course, it doesn't look good if it goes through object walls, tables etc.

**Comment by Lwmte** [comment]
I think it is original behaviour, and pretty much the same as with any other enemies. You should block the path with NOT WALKABLE block flag.

**Comment by illyaine** [comment]
This is difficult to do with objects that are naturally important for spatial geometry. So arcs (which go over 2 squares) and much more
I therefore have to do without the butler myself.

**Comment by Lwmte** [comment]
It is an original pathfinding issue. To limit ability of enemies to go through static meshes or moveables, NOT WALKABLE flag must be used.
