### ISSUE TITLE
[ Bug Report ] Lara can move when dragging SAS_DRAG_BLOKE

### ISSUE THREAD

**Issue by MatieTR** [MontyTRC89/TombEngine#1399]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

Lara can move around during the SAS_DRAG_BLOKE animation when pressing left or right direction keys. This is not intended and is not present in legacy engines. She also barely wants to grab it, which can easily make players give up trying to move the object and think it cannot be moved, which results in them getting stuck and frustrated.

Video demonstration:
https://streamable.com/ct4lsh

### To Reproduce

Using the TEN base wad make Lara grab the SAS_DRAG_BLOKE and move her by pressing left/right direction keys.

### Expected Behaviour

Lara should not be able to rotate around.

### Screenshots

https://streamable.com/ct4lsh

### Minimal reproduction project

https://www.dropbox.com/scl/fi/1endgmuiu873uz8mo9lyf/SAS_DRAG_BLOKE.zip?rlkey=tcgnmsd716sms732jwtcap3ob&dl=0

**Comment by Lwmte** [comment]
It looks like an asset issue. Try to change drag animation state ID to something else, e.g. to `PUSHABLE_PULL` (37).
