### ISSUE TITLE
[ Feature Request ] Changing room ambient light color

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/TombEngine#1409]
### Is your feature request related to a problem? Please describe.

Not an issue. A brand new feature.

### Describe the solution you'd like

There is already a **Room:GetColor()** function.
So it would be a good idea to also add a **Room:SetColor(Color(R, G, B))** function. So I don't need flipmaps to change it. Moreover, flipmaps cannot be used if I want more than two ambient light colors for a room.
I don't think I need to describe it, it is obvious what this feature is.

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by AkyV** [comment]
And something similar:
Is there a way to change the distance fog inside a level. I mean, **Flow.Fog** seemingly works only in gameflow.lua.

**Comment by Lwmte** [comment]
I am sorry, lack of ambient light change is on purpose. Rooms have baked-in vertex light. Changing ambient light won't actually change room lighting.
