### ISSUE TITLE
[ bug Report ] Buggy Objects.MoveableStatus constants

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/TombEngine#1411]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

I tested this:

```
LevelFuncs.OnLoop = function()
	local abc = GetMoveableByName("flame_emitter_1"):GetStatus()
	if abc == MoveableStatus.ACTIVE then
   		ShowString(DisplayString("active", 250, 350, Color(255,0,0)), 1/30)
   	elseif abc == MoveableStatus.INACTIVE then
    	        ShowString(DisplayString("inactive", 250, 350, Color(255,0,0)), 1/30)
   	elseif abc == MoveableStatus.DEACTIVATED then
    	        ShowString(DisplayString("deactivated", 250, 350, Color(255,0,0)), 1/30)    	
        else
    	        ShowString(DisplayString("invisible", 250, 350, Color(255,0,0)), 1/30)
        end	
end
```
The test results:
1. The flame is default (still inactive) when the level starts: inactive printed.
   Then the flame is triggered: active printed.
   Then the flame is antitriggered: text is still "active".
2. The flame is activated in the moment when the level starts: active printed.
   Then the flame is antitriggered: text is still "active".

Conclusion:
- The game detects only the active or inactive states.
- After triggerring the object, the game won't detect any other flag any more.

EDIT:
The same result with Moveable:GetActive() function.

### To Reproduce

See above.

### Expected Behaviour

See above.

### Minimal reproduction project

None.

**Comment by AkyV** [comment]
Sure!
[MoveableStatus_Test.zip](https://github.com/user-attachments/files/17118098/MoveableStatus_Test.zip)

**Comment by goldlife2904** [comment]
I debug a while and found the reason for this behavior:
`trigger.cpp` -> line 347 there is an if to check if status will be change or not, when antitrigger.
There is this:

```
if (item->Active && Objects[item->ObjectNumber].intelligent)
{
    DisableEntityAI(value);
    RemoveActiveItem(value, false);
    item->Active = false;
    item->Status = ITEM_INVISIBLE;
}

```

As the property "intelligent" from Flame Emitter itemnumber / Slot 359 is "false" the condition is not true, and the status will not change from active to invisible.

So either:
The condition makes no sense that there is query to "intelligent" (dont know why it is there)
Flame Emitter should be intelligent (but I think it is not intelligent ^^)
Status set outside the condition
