### ISSUE TITLE
Submarine makes Lara sounds

### ISSUE THREAD

**Issue by LGG-PRODUCTION** [MontyTRC89/TombEngine#1415]
When TR5 submarine (ATTACK_SUB) throws the torpedo, it makes Lara sounds

**Comment by Jakub768** [comment]
This types of issues are invalid. Can you please elaborate more? Have you checked wadtool if the sound is assigned there by accident.?

Also please next time create issues with provided bug report template - that is what it is there for.

**Comment by Lwmte** [comment]
Please recreate issue according to rules and provide minimal reproduction project.
