### ISSUE TITLE
[ bug Report ] Invisible Lara in the Hub system

### ISSUE THREAD

**Issue by davidmarr** [MontyTRC89/TombEngine#1417]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

In 2 levels connected with the “hub system” enabled in some contexts Lara becomes invisible 

### To Reproduce

In a hub level, there is an "end of level" trigger in a water room. When returning from the level to the hub, Lara becomes transparent at certain points.

If Lara goes into the water, she becomes permanently transparent. If I try to get out of the water, the game freezes but does not crash. 

If I go to the next level from the water room and return to the hub, Lara will be permanently transparent even outside the water. If I go into the water and try to get out of the water, the game freezes but does not crash. The log does not report any errors.

### Expected Behaviour

Lara does not have to become transparent

### Additional Content

Lwmte suspects it's a bug in the renderer. 
![image](https://github.com/user-attachments/assets/859fa935-4a84-46be-a344-ca775acedc25)
![image](https://github.com/user-attachments/assets/2c88fc99-1806-46fc-b7e9-11827ad7a45e)
![image](https://github.com/user-attachments/assets/9c77d015-5e3b-435e-83b3-c79ea4ba83b5)
![image](https://github.com/user-attachments/assets/2e8bd12f-3958-4ae6-9b97-c3dd9c82d975)

https://github.com/user-attachments/assets/42ed0ebe-194c-4e1a-9f23-405d7086a615

https://github.com/user-attachments/assets/08d108cc-003a-457a-85ba-0b71696a9967

### Minimal reproduction project

https://mega.nz/file/z5USUSDA#FFmnLezypOdaguCLY1qdAVcLL-M7ElVCNgrw2z9D0-U

**Comment by davidmarr** [comment]
l.m. had the same problem in his level

https://github.com/user-attachments/assets/e5717be9-5d0f-40aa-9ad6-06e80ad1b53d

Test level:
[DL.zip](https://github.com/user-attachments/files/17306990/DL.zip)

**Comment by goldlife2904** [comment]
choose Tremendous Tower Level to begin, pickup key, go through door, finish level to Georgous Gardens, then go back to first level and then lara will become invisible.

**Comment by Stranger1992** [comment]
Updated package: https://we.tl/t-VWqX6woG6P

**Comment by Lwmte** [comment]
Fixed
