### ISSUE TITLE
[ Feature Request ] Ability to bring pushables on collisionless statics

### ISSUE THREAD

**Issue by LGG-PRODUCTION** [MontyTRC89/TombEngine#1423]
### Is your feature request related to a problem? Please describe.

I'm making a level where there is a pushable that has to be pushed on a collisionless static, ut Lara can't,because the engine detects a minimal collision.

### Describe the solution you'd like

I would like if pushables can be pushed/pulled on an object with collision=0.

**Comment by Stranger1992** [comment]
@LGG-PRODUCTION please provide a test project.

**Comment by Adngel** [comment]
[collide_item.cpp]
GetCollidedObjects () (line 237)

```c++
auto box0 = bounds.ToBoundingOrientedBox(staticObj.pos.Position);
auto box1 = collidingBounds.ToBoundingOrientedBox(collidingItem.Pose);

// Override extents if specified.
if (customRadius > 0.0f)
    box1.Extents = Vector3(customRadius);

// Test accurate box intersection.
if (box0.Intersects(box1))
    collObjects.Statics.push_back(&staticObj);
```

Although box0 bounds extents are 0,0,0,0, it keeps sending to Intersect function, and this one just verify that the object is intersecting with box1 (that has the extent volume of the pushable) so returns a positive what push the static into the list of collided objects.

**Comment by Adngel** [comment]
Added fix in commit 0a8eb65de
```c++
auto box0 = bounds.ToBoundingOrientedBox(staticObj.pos.Position);
auto box1 = collidingBounds.ToBoundingOrientedBox(collidingItem.Pose);

// Override extents if specified.
if (customRadius > 0.0f)
	box1.Extents = Vector3(customRadius);

// Skip if either bounding box has any zero extent (not a collidable volume).
if (box0.Extents.x > 0 || box0.Extents.y > 0 || box0.Extents.z > 0)
	continue;

if (box1.Extents.x > 0 || box1.Extents.y > 0 || box1.Extents.z > 0)
	continue;

// Test accurate box intersection.
if (box0.Intersects(box1))
	collObjects.Statics.push_back(&staticObj);
```

**Comment by Adngel** [comment]
Because Extents is an XMFLOAT3, it doesn’t have an intrinsic .Length() function. Converting it to XMVECTOR to use the XMVector3Length function would add unnecessary complexity, so I kept this approach for simplicity and efficiency.

**Comment by Adngel** [comment]
Updated approach in commit: 0faa11a882cf011f4483a8dd3e1fc430a7f58aa6

**Comment by Lwmte** [comment]
Is it still happening?

**Comment by Lwmte** [comment]
Fixed, according to author's report.
