### ISSUE TITLE
[ bug Report ] The Flyby setting "Create tracking camera" flicker with the 60fps or develop branch

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#1425]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

The Flyby setting "Create tracking camera" does not work.
Bug is present in develop branch AND develop_60fps branch but NOT in 1.4 (in 1.4 it is work!)

### To Reproduce

Create two flyby camera.
First camera has ticked "Create tracking camera". Second camera nothing setting.
Trigger the first camera. 
Look that the screen wobbles.

### Expected Behaviour

Within TEN 1.4 it works.
The Screen does not wobbles and the "Create tracking camera" works.

### Minimal reproduction project

[Uploading DL.zip…]()

**Comment by goldlife2904** [comment]
https://github.com/user-attachments/assets/c4739efd-a293-4df2-b207-199a60aa7b06

**Comment by Lwmte** [comment]
Fixed
