### ISSUE TITLE
[ bug Report ] Lara does not pull the pushable correctly after Save / Load the game

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#1427]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

Lara does not pull the pushable correctly. She moves away while dragging the block and then gets pulled into the wall behind it and is off the map.
This happens only when you save and load the game. When starting the game and without save / load it still work correctly.
Bug is present in develop branch and also in v1.4

### To Reproduce

Start the attached Level (Tremendous Tower), save and load. 
Then try to pull out the pushable.

### Expected Behaviour

After Save and Reload the pushable should pull out correctly like it does when you enter the game without a reload.

### Minimal reproduction project

https://we.tl/t-lPz8w845dq?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05

https://github.com/user-attachments/assets/b0c1e83d-2d4e-433b-80f2-fea686a604b7

**Comment by Adngel** [comment]
Cannot reproduce in current develop version (28 / 10 / 2024).

I remember this bug was happening in TEN 1.4, but it dissapeared from develop at some point of the summer after some collision refactor.

**Comment by goldlife2904** [comment]
I think we can close it, because for I also cannot this reproducing any longer.
