### ISSUE TITLE
[ bug Report ] ENEMY_JEEP is causing issues with all moveable of the level

### ISSUE THREAD

**Issue by Christian-Croft** [MontyTRC89/TombEngine#1428]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

Ingame, all moveables including Lara are moved up when the ENEMY_JEEP object is placed inside any room.
In the video, we can see Lara falling at the beginning even though she is supposed to be on the floor.

(for the drift problem shown in the video, see issue #1429 )

https://github.com/user-attachments/assets/87611669-0c75-4fb8-a3f3-2367662cc641

### To Reproduce

Simply placing the ENEMY_JEEP item in the level, with or without trigger.

### Expected Behaviour

Ingame, moveable should stay exactly where they are inside the editor

### Additional Content

Tested on the latest public release (1.4) with no modifications.
Level created with TIDE and made with the latest public release Tomb Editor (1.7.1) with no modifications.

using the ENEMY_JEEP provided on the TEN website from the date of the 17th of October 2024.

### Minimal reproduction project

prj file and asset (script, textures and ENEMY_JEEP)
[bug_ENEMY_JEEP_files.zip](https://github.com/user-attachments/files/17422709/bug_ENEMY_JEEP_files.zip)

Playable level:
https://drive.google.com/file/d/1_bI71CSCOsEbwNUcPxGu5GLiqjVfVQQW/view?usp=share_link

**Comment by Jakub768** [comment]
https://github.com/MontyTRC89/TombEngine/pull/1395

**Comment by TokyoSU** [comment]
That's probably not the ENEMY_JEEP, he don't touch any objects except him.
