### ISSUE TITLE
[ bug Report ] ENEMY_JEEP does not follow AI_X1

### ISSUE THREAD

**Issue by Christian-Croft** [MontyTRC89/TombEngine#1429]
### TombEngine version

v1.4

### Tomb Editor version

v1.7.1

### Describe the bug

ENEMY_JEEP does not follow the path created with AI_X1 objects and simply drift away. 

https://github.com/user-attachments/assets/87611669-0c75-4fb8-a3f3-2367662cc641

### To Reproduce

Placing ENEMY_JEEP with several AI_X1 objects with OCB code starting from 0 to <31, as explained on the TEN website

### Expected Behaviour

ENEMY_JEEP should follow the AI_X1 in the order set with OCB.

### Additional Content

Tested on the latest public release (1.4) with no modifications.
Level created with TIDE and made with the latest public release Tomb Editor (1.7.1) with no modifications.

using the ENEMY_JEEP provided on the TEN website from the date of the 17th of October 2024.

### Minimal reproduction project

prj file and asset (script, textures and ENEMY_JEEP)
[bug_ENEMY_JEEP_files.zip](https://github.com/user-attachments/files/17422709/bug_ENEMY_JEEP_files.zip)

Playable level:
https://drive.google.com/file/d/1_bI71CSCOsEbwNUcPxGu5GLiqjVfVQQW/view?usp=share_link

**Comment by TokyoSU** [comment]
Enemy jeep was not added yet, you can found him in this PR: https://github.com/MontyTRC89/TombEngine/pull/1395
