### ISSUE TITLE
[ bug Report ] Unable to change keys in 60 FPS mode 

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1438]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

When trying to change keys in 60 FPS mode, it will not let you as it goes too fast and doesn't save.

### To Reproduce

Go to 60 FPS mode and try changing keys

### Expected Behaviour

Fixed behaviour

### Minimal reproduction project

None. Should happen everywhere.

**Comment by Lwmte** [comment]
Fixed
