### ISSUE TITLE
[ bug Report ] Lara cannot grab a Trapdoor when jumping up and the trapdoor is placed on a portal

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#1443]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

Lara cannot grap the trapdoor (which is placed on a portal) while jumping up. 

https://github.com/user-attachments/assets/b2222a76-5a88-49af-9bf0-0e5670ff8761

**Info:**
Lara can grap it normally when she is  standing on it and hop back down.
It works also when the trapdoor is moving up or down a bit (then it is not directly on a portal!)

it should be fixed, because many builders will place them on a portal (because it does in TRLE only work on a portal!!)

### To Reproduce

Open first level, jump up, Lara cannot grap the trapdoor

### Expected Behaviour

Lara should grab the trapdoor also when she jump up.

### Minimal reproduction project

https://leif.trlevel.de/levels/BUG_TRAPDOOR.zip

**Comment by Joey79100** [comment]
Looks very similar to this (which was closed by mistake):
https://github.com/MontyTRC89/TombEngine/issues/391
