### ISSUE TITLE
[BUG REPORT] - CRUMBLING_FLOOR below floor level 0 not working as intended

### ISSUE THREAD

**Issue by Mathew9R** [MontyTRC89/TombEngine#1444]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.1

### Describe the bug

Simply put, any CRUMBLING_FLOOR objects placed below Room Floor Level 0(Into minus) ceases to function correctly, losing all collision functionality and refusing to trigger.

### To Reproduce

Place any CRUMBLING_FLOOR object item below floor level 0(example, -6 floor height) and attempt to walk onto it, you will phase right through.

### Expected Behaviour

CRUMBLING_FLOOR should have collision and trigger upon stepping onto it like usual.

### Additional Content

This is a Developer Branch version of the Tomb Engine, CRUMBLING_FLOOR was downloaded from TEN website.

### Minimal reproduction project

https://drive.google.com/file/d/1ZUmLWLWWB1Rm1UYgtpMSrtiCwrZ-9SDv/view?usp=sharing

**Comment by Lwmte** [comment]
Fixed
