### ISSUE TITLE
[ bug Report ] Binoculars bugs

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#1448]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

The binoculars camera jumps when pressing look button to exit.

If you press escape while in binoculars, inventory opens up and the background shows Lara's headless body.

### To Reproduce

Go in binoculars, press look key or press escape key.

### Expected Behaviour

Camera should snap back immediately without any bounce.

Binoculars should exit when escape is pressed.

### Additional Content

https://www.youtube.com/watch?v=B8G8rRMASBc

### Minimal reproduction project

Any level can be tested

**Comment by Lwmte** [comment]
Fixed in 4aac07c0c4e1b0f883a838296db668a62ce313ab

**Comment by TrainWrack** [comment]
Hi Lwmte

The camera still jumps if you use escape or look button to exit the binoculars. 

Tested on 1.5 release

**Comment by Lwmte** [comment]
I havent noticed that you have 2 issues in 1 issue, sorry

**Comment by Lwmte** [comment]
Fixed in 1.7
