### ISSUE TITLE
[ bug Report ] important FPS drop when on/near stacked bridges

### ISSUE THREAD

**Issue by Christian-Croft** [MontyTRC89/TombEngine#1450]
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

When Lara is standing, running or simply is near stacked bridges, there is an important fps drop. Especially when bridges are set up in "stair" configuration (like the 2nd and 3rd configuration on the test level).

### To Reproduce

Stacking bridges on top of each other like stairs or similar to a staircase
<img width="519" alt="Capture d’écran 2024-11-03 à 16 16 14" src="https://github.com/user-attachments/assets/23745dcf-9a5f-47fd-8902-bf3209abf2a1">

### Expected Behaviour

Less fps drop when Lara is moving on stacked bridges

### Additional Content

Tested on 1.5 official release

### Minimal reproduction project

https://drive.google.com/file/d/1CwQHw7qhVS7NpFyQr4_JDBsooeNkpTMk/view?usp=share_link

**Comment by TrainWrack** [comment]
Hi @Lwmte 

I sent you a DM with my level as well. Just go to any tower and start climbing.

**Comment by Lwmte** [comment]
Fixed
