### ISSUE TITLE
[ bug Report ] Moveable animation has a jittery movement when looping at 60fps

### ISSUE THREAD

**Issue by AvrikV** [MontyTRC89/TombEngine#1452]
### TombEngine version

v1.5.0.2 (Latest Release)

### Tomb Editor version

v1.7.2

### Describe the bug

Certain looping animated moveables seem to "shake" with high framerate enabled. One moveable where this happens is with this escalator animation. This doesn't happen at 30 fps.

https://github.com/user-attachments/assets/ab235c21-95c1-445c-8e5b-d4f91f96104b

### To Reproduce

Place down the animated escalator (https://www.trsearch.org/item/5359), enable it, start game, and enable high framerate.

### Expected Behaviour

The object should snap back to the position on frame 1 instantly when looping.

### Minimal reproduction project

https://drive.google.com/file/d/1XDyV7yc0liXClLeU_R_jjs3JFj7qvaIU/view?usp=sharing

**Comment by Jakub768** [comment]
This has been discussed on our discord server., Can you try the following to the animating: Move "Disable interpolation" animcommand from the last frame to the first frame of animation in wadtool and check what happens.

**Comment by AvrikV** [comment]
Sounds like it will help but I can't find that option in the animation editor. Just has the other commands like set position, kill entity, etc.

**Comment by Jakub768** [comment]
> Sounds like it will help but I can't find that option in the animation editor. Just has the other commands like set position, kill entity, etc.

Developers forgot to put it there, should be available next version.

**Comment by Lwmte** [comment]
Fixed on TE side, flag is now available
