### ISSUE TITLE
[ Feature Request ] Reintroduce the ricochet sounds

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#1457]
### Is your feature request related to a problem? Please describe.

Since TR4 the ricochet sounds only occur when lara hits an enemy with some sort of shielding. I believe this is also the case in TEN.

### Describe the solution you'd like

An option to bring back the ricochet sounds like in TR1-3 whenever you can see the bullet hits wherever you are, ie walls/objects etc.

### Describe alternatives you've considered

N/A
(just dealing with it? haha)

**Comment by Lwmte** [comment]
Fixed
