### ISSUE TITLE
[ bug Report ] Snow causing heavy framedrops

### ISSUE THREAD

**Issue by neltharionn** [MontyTRC89/TombEngine#1458]
### TombEngine version

v1.5.0.2 (Latest Release)

### Tomb Editor version

v1.7.2

### Describe the bug

When enabling snow theres always a framedrop, sometimes its not very bad, but when the room in particular has elaborate lighting the framedrops are worse, disabling snow fixes it though.

### To Reproduce

Enable snow weather in the script for the level, then make a room and enable snow, add more lighting (try mixing them up aswell) bulbs and make a elaborate lighting.

### Expected Behaviour

You will notice a framedrop, sometimes to the point where its unplayable.

### Minimal reproduction project

https://www.mediafire.com/file/hrif1hajd73gok1/testlevels.zip/file

**Comment by illyaine** [comment]
Yes, I have to confirm that too. 
From 60 FPS before, it goes down to 15 FPS.
