### ISSUE TITLE
[ bug Report ] Lara's home does not work, not clickable

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#1459]
### TombEngine version

v1.5.0.2 (Latest Release)

### Tomb Editor version

v1.7.2

### Describe the bug

You cannot click on Lara's house from the title, even if everything is stored correctly in the script.

### To Reproduce

I have attached a playable folder with script and level, just start and click on Lara's Home.

### Expected Behaviour

.

### Additional Content

https://www.youtube.com/watch?v=DW4PUoLvEUI&feature=youtu.be

### Minimal reproduction project

http://devxs.de/TEN/LarasHomeTitleEntry.zip

**Comment by Lwmte** [comment]
Should be fixed now.
