### ISSUE TITLE
[ bug Report ] Look button produce a bug where room geometry breaks away

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#1471]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

When Lara is near a wall and the player press the "look" button all level rooms break away (for just a second).
The bug appears only in a specific room in my level, perhaps it has something todo with room setup or portals.

https://github.com/user-attachments/assets/b1448c9d-f0fd-4edd-93ec-9433b8878f39

### To Reproduce

DL Test Level, walk to a wall and Press "Look". 

### Expected Behaviour

Look Button does not produce this weird behavior.

### Minimal reproduction project

http://leif.trlevel.de/levels/BUG_LOOK_BUTTON_AT_WALL.zip

**Comment by Jakub768** [comment]
should be fixed in latest develop

**Comment by goldlife2904** [comment]
yeah it has fixed and we can close this issue when v1.5.0.3 has released and the bug is not present any longer.
