### ISSUE TITLE
AO causing lighting issues on imported geometry since 1.5.0.6

### ISSUE THREAD

**Issue by TrueRaiderr** [MontyTRC89/TombEngine#1486]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

Since the latest development build 1.5.0.6 ambient occlusion causes weird issues with lighting on imported geometry. 
[Imported Geo.zip](https://github.com/user-attachments/files/17872941/Imported.Geo.zip)
https://box.fu-berlin.de/s/3s9PFBNRp2rdzSw
In the level, open the test level. I've also included the object files.

![1](https://github.com/user-attachments/assets/f3515ff2-4e5c-4c31-a102-21265572816f)

### To Reproduce

--

### Expected Behaviour

--

### Minimal reproduction project
https://box.fu-berlin.de/s/3s9PFBNRp2rdzSw

**Comment by TrueRaiderr** [comment]
![Uploading 1.png…]()

**Comment by Lwmte** [comment]
Asset issue.
