### ISSUE TITLE
[ bug Report ] pushable_climbable blocks bug with the bridge

### ISSUE THREAD

**Issue by AlexxxQ** [MontyTRC89/TombEngine#1489]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

After moving the pushable_climbable blocks (435-437 slot) on the bridge in the opposite direction , Lara falls under the bridge. Old pushable blocks (393-395 slots) work perfectly.

### To Reproduce

the bug is produced only when pushing the block on itself, if you just push it  straight then everything works

https://github.com/user-attachments/assets/7398357a-4f76-4e83-8734-2067d2fab33b

### Expected Behaviour

//

### Additional Content

Test level is 1.6, TE 1.7.3

### Minimal reproduction project

https://drive.google.com/file/d/1xcQlYywM-DeBR_B-wiB0SlCnZNVvxyc3/view?usp=sharing

**Comment by Lwmte** [comment]
Fixed in dad63f98c5c0594eb1bdff79e6e27501b7750ca8
