### ISSUE TITLE
[ bug Report ] Strange sliding

### ISSUE THREAD

**Issue by Sabatu322** [MontyTRC89/TombEngine#1491]
### TombEngine version

v1.5.0.2 (Latest Release)

### Tomb Editor version

v1.7.2

### Describe the bug

![Untitled](https://github.com/user-attachments/assets/3a3a1590-71df-4921-9c79-6f7e57b64ab0)
Lara slides along the geometry in a completely wrong direction at some point.

THE PROJECT FILE

https://mega.nz/file/tMQhCKiT#WKCTl2QGZwi7lNJ0pk9NonLNGOr8d-R7h723px28OYo

### To Reproduce

![Untitled](https://github.com/user-attachments/assets/a199dbe0-444e-4931-8d05-fb86f79336dc)
Jump on the platfom in the video 
https://youtu.be/9geyzmDOBQo

### Expected Behaviour

She should slide down. I included the level.

### Minimal reproduction project

https://mega.nz/file/BdA3FIrA#wntRWNNls6oWkPJipYu9beI3u5nBrrughCTLLvrKNJY

**Comment by Jakub768** [comment]
seems to be fixed, reopen if not fixed
