### ISSUE TITLE
[ bug Report ] Light emitter (flame, strobe, pulse, color...) break shadow casting from an EmitLight

### ISSUE THREAD

**Issue by Christian-Croft** [MontyTRC89/TombEngine#1497]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

When a light emitter (flame, strobe, pulse, color...) is **active** far away from a dynamic light, with shadow parameter On, created through script (EmitLight() in that case), the shadow flickers.
When the light emitter is **active** near the dynamic light, the shadow from the dynamic light is not cast at all.

https://github.com/user-attachments/assets/7cf604d9-45fc-48e0-be04-db2024b1ccd9

### To Reproduce

By triggering a light emitter (flame, strobe, pulse, color...) near a dynamics light created through lua via the **EmitLight()** function with the shadow parameter set on **true**.

In the test level, it's a FLAME_EMITTER.

### Expected Behaviour

Since light emitter (flame, pulse and such) do not cast shadows, they should not interfere with the shadow casted by the EmitLight() function

### Additional Content

Using development build for TEN 1.6

### Minimal reproduction project

https://drive.google.com/file/d/1Pm5P9syld3gvLgOUc7_21OhIBVulo5vZ/view?usp=share_link

**Comment by Lwmte** [comment]
Fixed in 8edd446a6dd2e1c70ac220811ba56cc32151e1c6
