### ISSUE TITLE
[ bug Report ] "TEN.Strings.DisplayString" on a Loop will gradually collect Garbage and slow down ControlPhase

### ISSUE THREAD

**Issue by Mathew9R** [MontyTRC89/TombEngine#1499]
### TombEngine version

v1.5.0.2 (Latest Release)

### Tomb Editor version

v1.7.2

### Describe the bug

If you leave any "TEN.Strings.DisplayString" on a loop alongside "TEN.Strings.ShowString", it seems like some Garbage data is being built up which after a certain time period depending on how many are being looped will slow down ControlPhase to the point where the game starts breaking and FPS dies...that is until a Save or Level has been reloaded where the Garbage Data gets cleared.

This also affects the DrawText Nodes for Box Volumes.

### To Reproduce

Put "TEN.Strings.DisplayString" on a loop alongside "TEN.Strings.ShowString" or a Node "LevelFuncs.Engine.Node.DrawText" on loop and watch after about 15-20 minutes the ControlPhase starts to uptick in time and the FPS degrade to the point of severe breakage.

### Expected Behaviour

The Garbage Data which is being built up should always be culled where it wont at all affect ControlPhase.

### Additional Content

This has been happening on all versions ever since the ability to DrawText was implimented.

### Minimal reproduction project

No download since the problem is super simple to replicate.

```
LevelFuncs.OnLoop = function()
NodeTextLoop()
NormalStringLoop()
end

function NodeTextLoop()
	LevelFuncs.Engine.Node.DrawText("Node String Loop", 50, 1, 1, 1, TEN.Color(255,255,255), 0.75)
end

function NormalStringLoop()
	local TextCol = TEN.Color(255,255,255)
	local TextPos = TEN.Vec2(TEN.Util.PercentToScreen(50, 95))
	local TextText = "LUA String Loop"
	local TextDraw = TEN.Strings.DisplayString(TextText, TextPos, 0.75 , TextCol , false)
		TextDraw:SetFlags({ TEN.Strings.DisplayStringOption.SHADOW, TEN.Strings.DisplayStringOption.CENTER })
		
	TEN.Strings.ShowString(TextDraw, 1/30)
end
```

Just add that to a level script and leave running, watching ControlPhase degrade...or add multiple to speed up the degradion.

**Comment by Lwmte** [comment]
Thank you for the report! Indeed it was flooding the memory.
