### ISSUE TITLE
[ bug Report ] - GameVars do not take the HUB level change into account

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#1508]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

When I set GameVars.Test = 1 in Level A, go to Level B and increase that with GameVars.Test = GameVars.Test + 1  (in onStart() in Level B) and return to Level A there is only 1 instead of 2 in GameVars.Test

### To Reproduce

Start First Level, see the logs:

 [info] GameVars: 1

go to Level B (open door in front) see logs:

 [info] GameVars Level B: 2

and return to Level A 

 [info] GameVars: 1	

there is only 1 instead of 2 in GameVars.Test

### Expected Behaviour

After returning back to Level A it should log:

 [info] GameVars: 2

### Minimal reproduction project

https://leif.trlevel.de/levels/BUG_GAMEVARS.zip

**Comment by TrainWrack** [comment]
I do not think this was fixed.
