### ISSUE TITLE
[ Feature Request ] Expose GameCam Vec3 Position for LUA

### ISSUE THREAD

**Issue by Mathew9R** [MontyTRC89/TombEngine#1510]
### Is your feature request related to a problem? Please describe.

No problem perse minus the fact that Billboard Sprites placement in 3D space is apparently painful to impliment but I have LUA code which basically turns statics/moveables into "look at lara" objects and after testing this with flat plane meshes works pretty well, it's  like having TR1 billboard sprites again without all the hassle of natively supporting it through C++

### Describe the solution you'd like

Getting the current Cameras position as a Vec3 exposed to LUA under GetGameCamPos(vec3) likely under utility features, I know it exists as it shows up in debug stats so just expose it and allow us to use these pos.

### Describe alternatives you've considered

Actual game camera following lara around, its too buggy and a pain to get working, why do that when the sollution is right there.

### Additional context

If I was to add any additional context...yeah.

**Comment by Mathew9R** [comment]
Infact theres a lot of stuff in debug which could be exposed to utility section like fps and such, sometimes people will wanna know this stuff without using "-debug" command in a shortcut.

**Comment by Lwmte** [comment]
Was already implemented as `View.GetCameraPosition()`
