### ISSUE TITLE
[ bug Report ] Picking up flare item (not the flare_inv_item) gives 256 flars instead of 1

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1514]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

If you pick up a singular flare, it will give you 256 instead of 1 

### To Reproduce

place a signle flare on floor and pick it up, it willgive you 256 instead of 1 

### Expected Behaviour

should give you 1 flare or any x times depending on how many you placed

### Minimal reproduction project

Not atm

**Comment by Lwmte** [comment]
Fixed
