### ISSUE TITLE
[ bug Report ] ELECTRICAL_CABLES do not work

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1517]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

ELECTRICAL_CABLES does not work. it's primary function is to make water room deadly by hurting lara and provide electricity effect on Lara (or kill lara when she touches them) 

### To Reproduce

put ELECTRICA::_CABLES on the map where cables should touch the water.

### Expected Behaviour

the cables should hurt lara accordingly 

### Minimal reproduction project

not yet

**Comment by Lwmte** [comment]
Builder mistake.
