### ISSUE TITLE
[ bug Report ]level silently crashes when trying to buil and play level

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1522]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

When I do f5 or f6 option to build and play level, the level silently crashes with no log report. If I build level and launch from exe it works perfectly fine

### To Reproduce

try to launch my level that I provide below

### Expected Behaviour

shouldn't crash when I build and play level

### Minimal reproduction project

https://drive.google.com/file/d/1POwIAF0js6CQMqTsVRnhu4keMOoTRDen/view?usp=sharing

**Comment by Lwmte** [comment]
Provide a project file, not compiled level.

**Comment by Jakub768** [comment]
> Provide a project file, not compiled level - together with textures and wads.

Ok, I will send it to you over discord since github does not do DMs

**Comment by Jakub768** [comment]
Done. :)
