### ISSUE TITLE
[ bug Report ] Dynamic lights on Lara in mirrors not reflected past 1 square + slight flicker

### ISSUE THREAD

**Issue by MatieTR** [MontyTRC89/TombEngine#1524]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

Please ignore if this is intentional or if there is no easy way to fix it, it's only a minor visual quirk and can only really be noticed in a small threshold.

Description of observations:
- Dynamic lights affect mirrored Lara within 1 square while she's near the mirror itself.
- If you back away, there's a small threshold where light flickers on her mirrored image.
- If you go further back over 1 square the light she carries lights up the environment in the mirror, but not Lara.

Video:
https://streamable.com/e5wvvk

### To Reproduce

Light a flare or a torch and slowly back away from the mirror. 

### Expected Behaviour

Dynamic lights reflected on Lara just like her surroundings.

### Minimal reproduction project

https://www.dropbox.com/scl/fi/wlaq6l9tz68ua26c0vo00/Flare-and-lights.zip?rlkey=4di70rqqfhuszzfrs1u326z2q&dl=0

**Comment by Lwmte** [comment]
The reason for this bug is that reflected lights are not collected for reflected objects. To fix this, best option is to reflect lights in shader, not in C++ code.
