### ISSUE TITLE
[ bug Report ] Dynamic Lights not rendering/ Flares not illuminating player

### ISSUE THREAD

**Issue by Stranger1992** [MontyTRC89/TombEngine#1525]
### TombEngine version

Development Build - Tested with the mirrors branch (used for the pre-release version)
### Tomb Editor version

Development Build - Level compiled with the `master` branch **See below for different branch combinations**

### Describe the bug

Dynamic lights, produced with the `EmitLight` and `EmitSpotlight` functions are not showing in game. This seems to be a very recent regression. Furthermore, the light from flares do not illuminate lara until she throws them:

## Dynamic Lights not rendering

Tomb Editor node:

![image](https://github.com/user-attachments/assets/8da94c24-0d90-49a2-a228-a53b3e53c8e3)

Ingame:

![TEN-22-12-2024-16-18-25](https://github.com/user-attachments/assets/4e91fbcb-31fd-470e-8adb-e34c76c7a392)

## Flares not illuminating Lara

Whilst is holding a flare: it will not illuminate the player. Only when the flare is thrown and has detached from the player's hand will the dynamic light be cast.

![TEN-22-12-2024-16-18-38](https://github.com/user-attachments/assets/4b511f91-5952-45a0-b006-716289227c8c)
![TEN-22-12-2024-16-18-49](https://github.com/user-attachments/assets/e73f6ad6-1f24-43a4-84ba-f59f322119e4)

### To Reproduce

* Use the `Emit point light` node
* Light a flare

### Expected Behaviour

Dynamic lights should be rendered and flare lights should affect the player/

### Minimal reproduction project

n/a

**Comment by Stranger1992** [comment]
# Branch tests

## TEN `Develop` / Tomb Editor `Master`
* Flares illuminate Lara
* Dynamic lights from the nodes work.

**Comment by Lwmte** [comment]
Cannot be reproduced.

**Comment by Lwmte** [comment]
Fixed.
