### ISSUE TITLE
[ bug Report ] Doing a running jump and holding grab into certain walls makes you fall into the room below

### ISSUE THREAD

**Issue by AvrikV** [MontyTRC89/TombEngine#1527]
### TombEngine version

v1.5.0.2 (Latest Release)

### Tomb Editor version

v1.7.2

### Describe the bug

When Lara does a running jump and grabs into a certain type of wall, she'll clip through and fall into the room below.

### To Reproduce

This only happens with a specific layout but still kind of easy to run into by accident.
- Three rooms stacked on each other and connected with portals
- The room Lara is standing in has a wall that she does a running jump into and holds grab
- The room above has a raised floor tile on top of that wall so Lara can't reach the ledge
- The upper room is still low enough that Lara will go through the portal when she jumps
- There is a lower room with empty space that she falls into

https://github.com/user-attachments/assets/7d6e8a09-d0e0-494f-ae26-aa0730f77255

### Expected Behaviour

There shouldn't be any clipping into the wall.

### Minimal reproduction project

https://drive.google.com/file/d/1BNQYS4bm-gGM2caSWQuc8w0nbai6ekJf/view?usp=sharing

**Comment by Lwmte** [comment]
Please provide project file, not compiled level.

**Comment by AvrikV** [comment]
> Please provide project file, not compiled level.

Oops sorry about that.

https://drive.google.com/file/d/1x82AwHvA2VSV4lQjQW-UJyu-UHB_9BfJ/view?usp=drive_link

**Comment by Jakub768** [comment]
Hi @AvrikV thank you very much! 
We have released a new version today, could you check if the bug persists in the new version?

**Comment by AvrikV** [comment]
Hi tested out the new version and unfortunately it seems like the bug is still there. Really love the huge performance increase though.

**Comment by Jakub768** [comment]
> Hi tested out the new version and unfortunately it seems like the bug is still there. Really love the huge performance increase though.

Hello! Thank you for confirming! I think this bug is a floordata bug so I don't think it will be fixexd any time soon unfortunately.

**Comment by AvrikV** [comment]
No problem! The level I'm working on has a lot of vertical areas so I ran into it a couple times but it's not too gamebreaking.

**Comment by Lwmte** [comment]
This problem was related to TE not generating collision correctly in this particular case. It is fixed on TE repo.
