### ISSUE TITLE
[ bug Report ] If no title screen level is present game crashes

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#1538]
### TombEngine version

Development Build

### Tomb Editor version

Development Build

### Describe the bug

If no title screen is present the game crashes with the following error.

[2024-Dec-25 22:18:46] [error] Error while loading level: Level data block has incorrect size. Level version is probably outdated.

### To Reproduce

Delete the title level

### Expected Behaviour

The game should load with the embedded title file.

### Minimal reproduction project

-

**Comment by Jakub768** [comment]
Cannot reproduce this. My level has no title level present and built-in title level successfully launches.
