### ISSUE TITLE
[ bug Report ] Diary item is not present in inventory when reloading save

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#1543]
### TombEngine version

v1.7 (Latest release)

### Tomb Editor version

v1.7.3 (Latest release)

### Describe the bug

The DIARY_ITEM (986) disappears from inventory when reloading save.

I was hoping to use the existing slot for the TEN standard diary.

### To Reproduce

Put any pickup item in the DIARY_ITEM (986) object slot. Place it in level, pick it up, save game and reload. The diary item would disappear when reloading save.

### Expected Behaviour

The item should stay in inventory when reloading save.

### Minimal reproduction project

-

**Comment by Jakub768** [comment]
seems to be fixed in latest commit
