### ISSUE TITLE
[ bug Report ] Object camera view issue

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/TombEngine#1547]
### TombEngine version

v1.7 (Latest release)

### Tomb Editor version

v1.7.3 (Latest release)

### Describe the bug

The camera is out of the rooms.  Source: one bear, target: other bear.

![image](https://github.com/user-attachments/assets/1b1035cc-8e58-4bd3-980c-d4cc137e6162)

### To Reproduce

Files attached.
[Test Level.zip](https://github.com/user-attachments/files/18281803/Test.Level.zip)

### Expected Behaviour

As an object camera should behave.

### Additional Content

 -

### Minimal reproduction project

Attached above.

**Comment by Lwmte** [comment]
Fixed in 01129f62b5473835c28d9d5101637653c0af5bf8
