### ISSUE TITLE
Add support for all kinds of switches

### ISSUE THREAD

**Issue by wolfcheese** [MontyTRC89/TombEngine#324]
Currently level builders have to swap around switch animations and have a limited amount of options. We should see if there’s a way to expand that with TEN. 

Three options were brought up so far: 
1. adding more OCBs
2. using LUA to configure switches
3. using dedicated object slots for each switch type. 

Examples of switch types are big wall lever, small wall lever, big button, small button, wheel, and hole.

**Comment by Kubsy** [comment]
already done for TEN 1.0.2
