### ISSUE TITLE
Remappable key commands: Vehicle controls and weapon hotkeys

### ISSUE THREAD

**Issue by wolfcheese** [MontyTRC89/TombEngine#354]
Vehicle controls were discussed a little while ago. The issue is that vehicles originating from different TR games have different controls. From what I recall two options were brought up:

1. User setting between TR2 and TR4 style controls (TR3 controls seem unfavorable)
2. User settings for individual vehicle commands (accelerate, reverse, etc.)

On a similar note, with the plethora of weapons that the level designer can use together, it will be difficult to enforce a standardized hotkey mapping (for example, does pressing 5 equip the harpoon gun as in TR2, or the grenade gun as in TR4?) so it would be good to visit this topic for weapons as well. I can think of two approaches:

3. Level designer assigns weapon hotkeys 1-8 in LUA script
4. User settings for individual weapons (more flexible, but could get annoying to keep changing the settings when the next level they play has a different set of weapons)

**Comment by Kubsy** [comment]
implemented for TEN 1.1.0
