### ISSUE TITLE
Missing effects

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#365]
- [x] **Weather effects** - apparently rain and snow were not added during decompilation phase, I believe it can be restored from tomb5 code.
 - [x] **Underwater dust** - was added but later removed by Raildex
 - [x] #1263
 - [x] **Blob shadows** - legacy shadow type. Can be ported from tomb5 maybe?
 - [x] **Lara drips after exiting water**
 - [x] **Poisoned screen distortion** - when Lara is poisoned by darts or scorpion (do we need this at all? it's more suitable for first-person effect)
 - [x] **Fade-ins and fade-outs** - appear on level start/end and occasionally on cutscene start/end
 - [x] **Shininess** - maybe use static texture, as in tomb4/5 or [tomb1/2 framebuffer trick](https://www.tombraiderforums.com/showthread.php?t=226585)
 - [x] **Distance fog** - along with disabling rendering for all polygons beyond that
 - [x] **Volumetric fog** - was prototyped by Raildex but scrapped
 - [x] #1264
 - [x] **Animated textures framerate** - currently TEN doesn't write any data regarding animation sequence framerate.

**Comment by Kubsy** [comment]
Poisoned screen distortion - when Lara is poisoned by darts or scorpion (do we need this at all? it's more suitable for first-person effect) - this can be achieved with sprites and in Lua in general :)

**Comment by Lwmte** [comment]
Mirrors implemented in develop_mirrors
