### ISSUE TITLE
SEQUENCE_SWITCHes can't be used

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/TombEngine#390]
When you position Lara in front of them and press Action, she will start stepping back to align herself (but almost walk on the spot) for like 3 seconds, and then stop. And she never actually presses the switch

https://user-images.githubusercontent.com/12445716/146651896-174a0302-b1d8-4faf-8d07-3abbef02ac9c.mp4

.

**Comment by Joey79100** [comment]
I've just tested with TEN 1.0.8, and the issue is still there.
I didn't upload a test package before, here it is (using 1.0.8):
https://drive.google.com/file/d/1mFI-T1vrqRxi_VjQUMiac-GJwJAHq8Qo/view?usp=share_link

**Comment by Kubsy** [comment]
I think this has been discussed and we concluded it was an asset issue/hardcoded stuff from TR4. Closing feel free to reopen if this happens again tho
