### ISSUE TITLE
Shimmying: Lara does not move and shifts up slightly when corner shimmy on slopes

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#509]
Lara refuses to move to the right and she shifts up slightly
https://streamable.com/x4c88v

**Comment by asasas9500** [comment]
It is not an OG bug. The following video proves it:

[https://www.youtube.com/watch?t=380&v=cVJ_57lW44U&feature=youtu.be](url)

**Comment by Kubsy** [comment]
I believe it is fixed now.
