### ISSUE TITLE
Flame Emitter 1 (OCB -84 ) 

### ISSUE THREAD

**Issue by Stranger1992** [MontyTRC89/TombEngine#528]
Flame Emitter 1 (OCB -84 ) is supposed to be a horizontal flame. Randomly it is now vertical. 

![image](https://user-images.githubusercontent.com/84292688/172263173-c2e19e87-9c87-4788-a121-43eea8c6e147.png)

**Comment by Adngel** [comment]
In my case, testing the -84 ocb, it gives correctly an horizontal flame.

[flameEmitter1OCB.pdf](https://github.com/MontyTRC89/TombEngine/files/13330022/flameEmitter1OCB.pdf)
These are the OCB formulas I've got from the code.
