### ISSUE TITLE
Pushables collisions

### ISSUE THREAD

**Issue by WalrusTR** [MontyTRC89/TombEngine#550]
Pushable objects have a strange behaviour within flipmaps. 

![immagine](https://user-images.githubusercontent.com/43911310/174083276-f76bc3b4-9d9c-404b-a3e5-a076793779c2.png)

Pushable 1 has furthermore this odd behaviour where it can't be pushed forward if it isn't pushed back once.

Pushables need to be moved to trigger an animating on the room above that unlocks a switch, which triggers the flipmap. When the flipmap is triggered, all the three pushable have a collision block next to them that can't be moved.

From [here](https://www.dropbox.com/s/ishlsefcyhsmtnv/sib1_PushableErrors.rar?dl=0) you can download project, tga, wad2, scripts and compiled .trc

**Enhancement suggestion:**
As future enhancement, it would be interesting prevent pushable pushing/pulling if there is a static mesh on the block where it is not supposed to be moved by Lara.

**Comment by Adngel** [comment]
In the pushables remake, I edited several issues that generated an error like this (specifically, a problem with how the pushables were populating the "Stoppable" flag in the tiles around them).

This situation described in this issue shuldn't happen anymore in the remake pushables.

**Comment by Adngel** [comment]
Fixed applied in version TEN 1.2
