### ISSUE TITLE
Dragon: Epic lag drop when the dragon does certain actions

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#561]
It seems to lag when it starts to fire.
https://streamable.com/yz66kw
https://streamable.com/mdg8xx
https://streamable.com/9jty9b

here's prj2
https://drive.google.com/file/d/1gIDGuTQRX222bjWO_3HChCGwt_18Z33Q/view?usp=sharing

**Comment by Adngel** [comment]
Dragon implemented after several reworks. This issue is refering to a very old version. Clossing issue.

If problem would arise again, please report back with updated data.
