### ISSUE TITLE
Wrong scissor tests

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#571]
After Raildex found out that we had DX debug logging disabled for more than a year, an issue surfaced. It seems that scissor tests aren't done properly, which causes log spamming:

![Clipboard_1](https://user-images.githubusercontent.com/3331699/176628439-8956415d-562d-4b29-a33b-ecfcdd8991e4.jpg)

Apparently it seems that rectangle left is always bigger than rectangle right. Flipping them fixes scissor test log errors, but visual artifacts start to appear. So the problem must be something else.

**Comment by Kubsy** [comment]
i think this has been solved with Monty's recent renderer fixes, closing.
