### ISSUE TITLE
Crocodile: Strange behaviour when different entities are in WAD

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#623]
I have a DOG in my wad and it does strange stuff (takes anims and states from the DOG)

https://user-images.githubusercontent.com/80340234/181996494-4e71ab34-8c73-48c1-966c-e1202dfa522f.mp4

This also happens when HARPY is in the WAD

**Comment by Adngel** [comment]
Crocodile has many issues, but this is one I can't replicate. 
I assume is has been fixed time ago on any update. I close issue.

Please if this behaviour reappear, open a new report or update this one with the new information.
