### ISSUE TITLE
Game hangs after switching windows sometimes (windowed mode)

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#625]
![unknown](https://user-images.githubusercontent.com/3331699/182021456-8f8e3502-7208-4d97-8206-811e77fc1731.png)

**Comment by Kubsy** [comment]
I did not notice this and no one reported this thus far. Should I close?

**Comment by Lwmte** [comment]
It seems to be related to console switching to "quick edit" mode. Not fixable without affecting accessibility of console window.
