### ISSUE TITLE
Slowdowns when flare/rocket/grenade is spawned in Kamillos test level

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#626]
![unknown](https://user-images.githubusercontent.com/3331699/182021500-2cd20d40-bfba-4001-a601-0d5eccb001f1.png)
![unknown aaaaaa](https://user-images.githubusercontent.com/3331699/182021512-542ced0b-215f-42f9-94c6-d299b3ccea7c.png)

level: https://discord.com/channels/218414493355606016/481099779611295747/999359520688066751

**Comment by Kubsy** [comment]
this doesn't happen anymore with monty's recent renderer fixes. will close for now
