### ISSUE TITLE
Locusts and Little beetle do not receives room ambient light.

### ISSUE THREAD

**Issue by Adngel** [MontyTRC89/TombEngine#632]
The spawned locusts and little beetles, apears in black color, only getting visible with room light bulbs and dynamic lights (like gun shoots, or flares).

During the tests, it was tried to change the line:

Renderer11Draw.cpp, line 698
_m_stStatic.LightMode = moveableObj.ObjectMeshes[0]->LightMode;_

Into the next ones:
_m_stStatic.LightMode = LIGHT_MODES::LIGHT_MODE_DYNAMIC;
and
m_stStatic.LightMode = LIGHT_MODES::LIGHT_MODE_STATIC;_

Neither of them fixed the issue.

There is a chance the problem were on the mesh object from the wad, once a new mesh with correct normals were available, more tests and updates will be done to this issue.

**Test Level:** https://drive.google.com/file/d/1dzOmRAZuKpZ-LyMOC4_NybqHvozTJfgt/view?usp=sharing

**Comment by Lwmte** [comment]
Was fixed in renderer refactor branch.
