### ISSUE TITLE
Monkeyswing ignored if placed under trapdoors in stacked rooms

### ISSUE THREAD

**Issue by WalrusTR** [MontyTRC89/TombEngine#681]
Monkeyswing apparently is ignored by Lara if it's placed under trapdoors only in stacked rooms. In TRNG set the blocks as monkeyswing in the rooms **_above_** the trapdoors and in the room where they are placed, make MS working again but TEN ignores this setting. 

Test level is attached both as TEN and TRNG version.

[monkeyswing_issue.zip](https://github.com/MontyTRC89/TombEngine/files/9363880/monkeyswing_issue.zip)

**Comment by Lwmte** [comment]
I can't reproduce this issue. It works if you apply monkeyswing to the same room where trapdoor is placed:

1) Remove portal from the block where you want to apply monkey flag
2) Apply monkey flag to a solid block
3) Reapply portal to the block
4) Place trapdoor / bridge on that block
5) Observe it working
