### ISSUE TITLE
Puzzle_Item_combo items are not combinable after adding them to gameflow file

### ISSUE THREAD

**Issue by kamillos1003** [MontyTRC89/TombEngine#691]
Before I script them, they can be combined, but after i do that, they are no longer combinable:
![image](https://user-images.githubusercontent.com/75733118/185809975-c7928076-7c21-4b45-92dd-61b798259331.png)

**Comment by Adngel** [comment]
There is a fix for this already in develop. Which will come with the next version.

Be aware that when define an item in Gameflow.lua, you will need to indicate the item actions. Example:

```
MyLevel.objects = {
	InventoryItem.new(
		"HorusEye_1",
		ObjID.PUZZLE_ITEM1_COMBO1,
		0,
		0.5,
		Rotation.new(0, 0, 0),
		RotationAxis.Y,
		-1,
		ItemAction.USE | ItemAction.COMBINE
	),
	InventoryItem.new(
		"HorusEye_2",
		ObjID.PUZZLE_ITEM1_COMBO2,
		0,
		0.5,
		Rotation.new(0, 0, 0),
		RotationAxis.Y,
		-1,
		ItemAction.USE | ItemAction.COMBINE
	),
	InventoryItem.new(
		"HorusEye",
		ObjID.PUZZLE_ITEM1,
		100,
		0.5,
		Rotation.new(0, 0, 0),
		RotationAxis.Y,
		-1,
		ItemAction.USE
	)
}
```

With this solved, I close issue.
