### ISSUE TITLE
CRUMBLING_FLOOR doesn't launch the level - throws back to the title

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#697]
If I put a CRUMBLING_FLOOR object in the level and try to run the level, then it fails and throws me to the title with error log saying: "Bad function call"

**Comment by hispidence** [comment]
Unassigning myself from this; I looked into it but it seems the main issue is that it just hasn't been decompiled (which I don't yet have the expertise to tackle myself).
