### ISSUE TITLE
Box Volume, OnLeave function not called when leaving Room

### ISSUE THREAD

**Issue by popzelife** [MontyTRC89/TombEngine#747]
If a Box Volume is put next to a portal, the onLeave function is not called when Lara leave the Box Volume to enter a different room.

![image](https://user-images.githubusercontent.com/9898633/191498561-c56128aa-33eb-4a94-a823-31e1461297db.png)
On example picture Box Volume is put on red square (2D map) next to 2 portals. If Lara leaves Box Volume Eastward or Southward, onLeave function is never called, as she leaves the room and enters a different room.
But OnLeave function is called if Lara leaves the Box Volume and stay in the same room (West and North direction here).

OnEnter function works fine.

**Comment by Kubsy** [comment]
Lwmte said it is not supported so closing.

**Comment by popzelife** [comment]
While it is not supported or implemented (yet?), it should be documented because it's not obvious for builders and may lead to confusions ;)
