### ISSUE TITLE
Properly introduce all of the used OCB values for all of the possible objects.

### ISSUE THREAD

**Issue by ShadowXJaw724** [MontyTRC89/TombEngine#748]
Adding corresponding values to the WIKI will be a definitive help to many people, and nothing which items do have OCB's and which do not.

**Comment by Kubsy** [comment]
https://github.com/Stranger1992/Tomb-Engine-Demo-Levels/wiki/New-OCB-and-Setup-Instructions-for-Legacy-Objects
