### ISSUE TITLE
shotgun_ammo1_item and shotgun_ammo2_item gives 1 when picking up bullet box

### ISSUE THREAD

**Issue by diebasis72** [MontyTRC89/TombEngine#752]
Picking up one box of shotgun_ammo1 or one box of shotgun_ammo2 gives only 1 bullet instead of 6.
Default was 6.

![Unbenannt_2](https://user-images.githubusercontent.com/58602705/192155791-7db6281a-235d-4c35-aa77-9e4dce418aa8.jpg)

Another Example: 
If I set "GiveItem(ObjID.SHOTGUN_AMMO1_ITEM,36) I get 6 bullets in inventory.

![Unbenannt 2](https://user-images.githubusercontent.com/58602705/192155536-a5f08ee3-8efb-4fee-a88e-533f45135035.jpg)

So amount you set is divided by 6.

Additional information:
Apparently shotgun_item itself doesn't also have ammo preloaded anymore.

TEN version tested was 1.0.2

**Comment by Sezzary** [comment]
Fixed for 1.0.3. :)

It appears none of the weapons have ammo preloaded anymore. That may have been intentional. A future refactor of the weapons system may rectify this, but for now, I think we can live with it.
