### ISSUE TITLE
Pushables don't make any sound

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#754]
I use the default TEN lara.
I check that xml and in my level there is the Sound with ID 63 PUSHABLE_SOUND green (Level Settings / Sound Infos)
Also there is a sound present in my sound folder.
Other sounds does not have a problem - but this pushable sound.

**Comment by illyaine** [comment]
As far as I know, the pushable sound is controlled by the engine. It is not stored in the animation in the original WADs.
For me, despite the assignment of the sample in the TE, there is no sound when pushing/pulling the pushable.

**Comment by Kubsy** [comment]
Yes in TRNG it is hardcoded and controlled by the engine. However, in TEN this might not be the case anymore.

**Comment by illyaine** [comment]
Not only in the TRNG engine, also in the original engine of Core Design.

**Comment by goldlife2904** [comment]
Yes I check it. 
I also add an entry in the animation editor - look at the pitcure.

![iDhdUrsBet](https://user-images.githubusercontent.com/75839472/192841946-f5896b1f-e88f-409b-9946-0fe1456f0c70.jpg)

No sound...
