### ISSUE TITLE
Distance Fog - Transparency Bug

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#755]
There is the good old transparency bug if you use distance fog.
Transparent objects and textures are much to bright if there is distance fog enabled.

![1](https://user-images.githubusercontent.com/75839472/192824049-b9c952ea-682a-4c34-b6a1-bb57d4ba3fde.jpg)

**Comment by Lwmte** [comment]
Should be fixed on `transparent_fog` branch.

**Comment by goldlife2904** [comment]
was fixed  👍
