### ISSUE TITLE
Set collision type directly in the Tomb Editor - like this Static:SetSolid(if)

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#762]
Would it be an idea (or would it be possible at all) to have an option in the TE that allows us to specify the collision type in the context menu of a static? By default every static has a hard collision Static:SetSolid(true). I would like to be able to right click in the editor on some objects like plants / trees, etc) and set them to "soft collision". I know I can script it with LUA. But it is annoying to script this manually for every object in my level where I want this soft collision "Static:SetSolid(false)".

Soft Collision "Static:SetSolid(false)" is for this kind of collision where you can run further in front of the object by holding down the forward key (it runs on the spot). Hard collision is the type of collision where Lara stops abruptly (even with the forward button pressed).

See here: https://lwmte.github.io/2%20classes/Objects.Static.html#Static:SetSolid

SetSolid(true) is the Hard Collision (default), 
SetSolid(false) is the soft collision.

**Comment by Lwmte** [comment]
Planned.
