### ISSUE TITLE
massive bug with monkey and diagonal wall

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#766]
I found a massive bug, when you have 2 rooms and below is a diagonal wall and on the ceiling of the 2nd room (stacked) has monkey, Lara will not go straight and the edge seems to be a diagonal.

This is like as if the diagonal wall below the room is making a diagonal line at the ceiling and Lara cannot pass it.

https://user-images.githubusercontent.com/80340234/194726740-4e97b6ee-1ca4-4c95-8170-c89a951169b6.mp4

![image](https://user-images.githubusercontent.com/80340234/194726756-1adccfed-1d53-4ac5-8536-72946802347a.png)

**Comment by Lwmte** [comment]
Not related to TEN.
