### ISSUE TITLE
Classic_Rolling_Ball and Big_Rolling_Ball disappear when triggered

### ISSUE THREAD

**Issue by diebasis72** [MontyTRC89/TombEngine#773]
As title says, Classic_Rolling_Ball (Slot 433 and Big_Rolling_Ball (Slot 434) e.g. from TR3 disappear when triggered.

According to KlokBier they worked in the first beta version of TEN.

>  Originally Posted by KlokBier on trf
Speaking of Rollingballs, did anyone get classic rollingball to work? When TE beta was just released it worked. Now it just seems to dissapear when I trigger it. (Same applies to Temple of Puna giant rollingball)

![Unbenannt 2](https://user-images.githubusercontent.com/58602705/195393500-506242a6-c3d2-4234-9bb7-5adf57436d5a.jpg)

**Comment by Kubsy** [comment]
this seems to be fixed in 1.0.3 but their movement is not good.
