### ISSUE TITLE
Feature Request - Divide wall more than 4 times, especially portals

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#778]
Currently you can only subdivide a wall 4 times and a wall with a portal only once.
It would be better if it could be subdivided more often, especially the wall near the portal.

![portal1](https://user-images.githubusercontent.com/915558/195976528-737aea13-5ed5-4f5c-896a-da43174f9d90.jpg)
![Portal2](https://user-images.githubusercontent.com/915558/195976530-495917a9-8a08-4a39-b929-59e19547ac20.jpg)

**Comment by Kubsy** [comment]
and also this I think that's the job for Tomb Editor 👀

**Comment by illyaine** [comment]
Right. Wring repo, too. Sorry
