### ISSUE TITLE
Feature Request - Divide floor/ceiling square

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#779]
![floor](https://user-images.githubusercontent.com/915558/195976586-f5a06902-eb64-4a38-a570-a11f0188cb43.jpg)

If you can subdivide the floor/ceiling square again, then you could build something "smoother" architecture in the level.

**Comment by Kubsy** [comment]
I think that's the job for Tomb Editor 👀

**Comment by illyaine** [comment]
Yes, that's right.  I put it in the wrong repo.
