### ISSUE TITLE
Feature Request - Realistic Waterfall

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#780]
https://www.twitch.tv/videos/463943354?filter=all&sort=time

7:30 Minutes

In the following video, MrXY introduced the then The Last Saga 5 exe by Tomo. There are generally great effects included in this video.
But here at 7:30 a great waterfall can be seen. Tomo had realized this with the waterfall mist and various OCB codes.
In any case, such a waterfall would of course greatly enhance a level, since the whole thing is currently only possible via a waterfall object or texture.

![Waterfall](https://user-images.githubusercontent.com/915558/195976771-6e18dd10-3a4e-4111-9cfc-bb17c352dd4a.jpg)

**Comment by Lwmte** [comment]
This is an ordinary particle emitter which is already possible via lua scripting. Therefore, no need for such request.
