### ISSUE TITLE
Feature Request - Save flyby sequence (export and import for publication)

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#786]
It would be useful if you could save existing flyby sequences. This would make sense if you build corresponding cutsequences and laboriously adjust the camera to the animations, but want to use this cutsequence over several levels, you don't always have to reposition the flyby.
You could then possibly even make this flyby sequence available for download for other level builders.

E.g. the TR4/TR5 cutsequences by Sapper. I had already installed one from TR4 in my level, the flyby sequence had cost me a good two hours of work.

https://www.trsearch.org/item/3531

**Comment by Lwmte** [comment]
TE feature request.
