### ISSUE TITLE
Feature Request - Rework water rooms (rising/falling water)

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/TombEngine#789]
Unfortunately, rising and sinking water spaces can currently only be built in to a limited extent, if then of course with a lot of work on flip maps, rooms, etc.

It would be an idea if you could define water spaces differently, e.g. "Water Box" and you could drag/push/enlarge/reduce them etc. accordingly.
This could then be adjusted with Lua etc., for example, so that the water rises/falls etc.
Of course, it also has to work with the vehicles (motorboat, kayak, etc.).

**Comment by Lwmte** [comment]
Unrealistic feature request which is not possible in classic TR engine.
