### ISSUE TITLE
TR3 Sounds with chance value unequal 100% are not audible at all

### ISSUE THREAD

**Issue by JohnnyJF10** [MontyTRC89/TombEngine#797]
If a sound is assigned with a chance value unequal 100 percent in the MAIN.SFX the sound is not audible at all in case the level is built with Tomb Editor.

The Tomb Editor Wad Conversion Tool maps the chance percentage to a byte which the TR3 engine is unable to use (for an unknown reason). For instance: 
Percentage ----- Byte value
50%--------------128
10%--------------26
90% -------------230

As mentioned, the TR3 engine is not able to work with these byte values. By observations on original level files from TR3, the correct byte values would be as follows:
Percentage ----- Byte value
50%--------------127
10%--------------25
90% -------------229

The following correction in the Wad Converter is proposed to fix the issue:
In the Tomb-Editor/TombLib/TombLib/LevelData/Compilers/Wad.cs / in line 929 replace the Math.Round function with the Math.Floor function. 

Current: newSoundDetail.Chance = (byte)Math.Round((soundDetail.Chance == 100 ? 0 : soundDetail.Chance) / 100.0f * 255.0f);

Proposed: newSoundDetail.Chance = (byte)Math.Floor((soundDetail.Chance == 100 ? 0 : soundDetail.Chance) / 100.0f * 255.0f);

https://github.com/MontyTRC89/Tomb-Editor/blob/8a05a8f4b26b319b78ae2dc43f2f037b94cd50fa/TombLib/TombLib/LevelData/Compilers/Wad.cs#L929

For reference, please find the following thread on www.tombraiderforums.com:
https://www.tombraiderforums.com/showthread.php?t=227598

**Comment by Lwmte** [comment]
This is TE issue, not TEN issue. Nevertheless, fix is now on `ten_beta` branch, please check it out.

**Comment by JohnnyJF10** [comment]
Ah yes, you are totally right, now I was also realizing. Sorry for inconvenience.

**Comment by JohnnyJF10** [comment]
Hi Lwmte, 

TR2 has a sounds chance issue as well, which can also be fixed. 

For TR2 we have in line 919 ([https://github.com/MontyTRC89/Tomb-E...rs/Wad.cs#L919](https://github.com/MontyTRC89/Tomb-Editor/blob/8a05a8f4b26b319b78ae2dc43f2f037b94cd50fa/TombLib/TombLib/LevelData/Compilers/Wad.cs#L919)) the formula:
 
newSoundDetail.Chance = (byte)Math.Round((soundDetail.Chance == 100 ? 0 : soundDetail.Chance) / 100.0f * 32767.0f);

After some testing I am convinced this formula defenitely does not work as intended for a chance unequal 100% (For 100% chance it is fine). With the cast to byte the formular will not produce reasonable output.

The cast should be for ushort, because the chance field in the tr_sound_details struct is also ushort ([https://github.com/MontyTRC89/Tomb-E...ructs.cs#L1212](https://github.com/MontyTRC89/Tomb-Editor/blob/8a05a8f4b26b319b78ae2dc43f2f037b94cd50fa/TombLib/TombLib/LevelData/Compilers/Structs.cs#L1212)) and the floor function should be used here as well.

So this would be a possible fix, already tested:

newSoundDetail.Chance = (ushort)Math.Floor((soundDetail.Chance == 100 ? 0 : soundDetail.Chance) / 100.0f * 32767.0f);

**Comment by Lwmte** [comment]
What about TR1 though? Does it also work correctly in such case?

**Comment by JohnnyJF10** [comment]
Yes for TR1 it fixes the chances issue as well. 

For TR2 and TR1 in case of the LARA_JUMP sound there are some differences. 

In TR1 the chance for LARA_JUMP is 49. 

The formula in line 919 ([https://github.com/MontyTRC89/Tomb-E...rs/Wad.cs#L919](https://github.com/MontyTRC89/Tomb-Editor/blob/8a05a8f4b26b319b78ae2dc43f2f037b94cd50fa/TombLib/TombLib/LevelData/Compilers/Wad.cs#L919)) outputs  184 in this case, very small compared with the maximum 32767, so you will never hear the LARA_JUMP sound with TE generated TR1 levels. (Correct should be 16055)

In TR2 the chance for LARA_JUMP is 50. 

The formula in line 919  outputs 0 in this case (because of the casting to byte), so you will always hear the LARA_JUMP sound with TE generated TR2 levels. (Correct should be 16383)

Using the corrected 919 line fixes the issue in both cases and does not mess up anything else.

**Comment by Lwmte** [comment]
OK then, I introduced a fix for TR1-TR2 sound details packer as well. Please check if `ten_beta` branch on TE repo now produces correct output for TR1-3.

**Comment by Lwmte** [comment]
Addendum: using chance values above 50 in TR3 won't properly work, this is an engine issue, as discovered by Troye/ChocolateFan. It won't be fixed TE-side.

**Comment by JohnnyJF10** [comment]
Yes I checked all three engines, everything seems fine. 

By the way some other sounds characteristics are different as well when comparing TE generated levels with stock levels. This however, does not seem to be very noticable like the chances characteristic.
