### ISSUE TITLE
Lara can't climb up a ledge when destination square has a triangle

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#803]
There is a problem with Jump and Grab / pull up onto a ledge in the master TEN - look at the video.. 

https://imgur.com/ke0TrZ8

Ledge Construction in TE:
![TombEditor_RguJkaD3o8](https://user-images.githubusercontent.com/75839472/197817691-8195d803-a3af-4292-af51-18d321e4da80.jpg)

**Info:**
When the red square is change to normal square instead of triangle it works.

**Comment by Lwmte** [comment]
You need to provide test project to reproduce this.

**Comment by Lwmte** [comment]
Fixed in #807
