### ISSUE TITLE
sfx (holsters) do not play when put into one hand weapons like crossbow

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#810]
if you put a sfx to a crossbow animation where lara equips it (say a holster sound) then it will either: not play at all or it will play however it will play at a very low volume and not in the settings set in soundtool.

However for pistols it works completely fine.

https://user-images.githubusercontent.com/80340234/199220725-97f21d7b-8857-4b69-97b9-200ff6447e5c.mp4

**Comment by Lwmte** [comment]
Fixed
