### ISSUE TITLE
Tomb Editor: Diagonal wall with ceiling division on edge of portals creates a rogue triangular block on one side

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#813]
![image](https://user-images.githubusercontent.com/111427436/199474979-75220263-2604-4000-873e-b02684cb1460.png)
As shown in the screenshot, when using subdivided diagonal ceiling tiles on the edge of a room there'll be a rogue triangle attached to the bottom part of the ceiling from the top.

**Comment by Lwmte** [comment]
Wrong repo, closing issue.
