### ISSUE TITLE
Items pried from the wall don't show up in inventory only the name

### ISSUE THREAD

**Issue by diebasis72** [MontyTRC89/TombEngine#819]
Don't know if that has already been noticed, but as you can see in picture:

Items pried from the wall don't show up in inventory only the name.

I tried with black beetle from Tomb Raider IV and the coin from TR V.

![Unbenannt 5](https://user-images.githubusercontent.com/58602705/199953443-f293ac13-b852-4802-b0f9-15c7e134e0ec.jpg)

**Comment by Kubsy** [comment]
@diebasis72 can you check if it appears by modifying the yOffset in gameflow.lua?

**Comment by Adngel** [comment]
I'm getting similar problem.

However I think the reason is a requirement or polishment in the position at the item definition in gameflow.lua script. I will update when I get more info.
