### ISSUE TITLE
Waterfall objects are not rendered correctly

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#833]
the actual master branch broke the waterfall objects ... 😦
In TE:

![TombEditor_wn4a22hGwa](https://user-images.githubusercontent.com/75839472/201423076-79a8623a-c3df-4c11-b40c-5706070f6d4d.jpg)

Ingame only small flickering objects:
https://imgur.com/hTFe5Rb

**Comment by Lwmte** [comment]
Fixed in d8dbbdf110f289a37b5f26e02a2bad6fcd167978
