### ISSUE TITLE
Default Weapons and Items Do Not Load After "Build and Play Level"

### ISSUE THREAD

**Issue by Stranger1992** [MontyTRC89/TombEngine#848]
Check this video.

You can see that I do a fresh compile of the level, then the game loads straight into the level. No pistols, no inventory items. However this is fixed when exiting the level and going back into it.

_TEN Build: Master Branch (14th November 2022), 
TE Build: Master Branch (14th November 2022).

First started occurring approximately a month ago._

https://user-images.githubusercontent.com/84292688/201804604-156bd4e0-9d19-417a-9340-846db6f9f48d.mp4

**Comment by Lwmte** [comment]
Fixed in b2313873959bc102d1b2d67186e05501dace0840
