### ISSUE TITLE
Incorrect sounds and state ids 

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#851]
I noticed that some objects have wrong sounds attached to them. I managed to fix them myself in wadtool but everytime a user creates a TEN wad then they have to keep fixing them.

**Comment by Stranger1992** [comment]
Hi

Can you be specific as to which have the wrong sounds ?

Are you using the most update to date version of Tomb Editor? Because they
remap across fine .

**Comment by Kubsy** [comment]
- lara when climbing up on a shelf, there should be a metal sound playing but another sound plays LOOT_SHELF frame 123
- wrong harpoon guns 
- no chest opening sfx
- wrong valve sfx on frame 129 of VALVE_TURN animation
- no cabinet opening sfx LOOT_CABINET
This is just few I noticed but there may be more.

**Comment by Kubsy** [comment]
and yes i am using up to date TE

**Comment by Stranger1992** [comment]
Changed the title of this issue because it is misleading and heavily implied ALL sounds and stateIDs were incorrect which really isn't true. 

Any amendments will be completed in due course when reported.

**Comment by Stranger1992** [comment]
> * [x]  lara when climbing up on a shelf, there should be a metal sound playing but another sound plays LOOT_SHELF frame 123
> * [x ]  wrong harpoon guns
> * [x]  no chest opening sfx
> * [x]   wrong valve sfx on frame 129 of VALVE_TURN animation
> * [x]  no cabinet opening sfx LOOT_CABINET

"wrong valve sfx on frame 129 of VALVE_TURN animation" is subjective. It is copied based on the TR5 sinking sub. 
"No Cabinet opening" fixed.
"No Chest Opening SFX" added. Not the original sound used but one I think fits better.
Removed Harpoon Gun draw sound effect when underwater.
