### ISSUE TITLE
garbage frame when lara rolls underwater

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#856]
https://user-images.githubusercontent.com/80340234/202774785-ffd6ff5d-a6d3-47d9-aaf7-77230b0b4b41.mp4

**Comment by Kubsy** [comment]
> Thats interesting as the animation does not have any garbage frame.

Then it's probably an oopsie in the code

**Comment by Lwmte** [comment]
Cannot reproduce. Most likely oopsie in your assets. Provide wad.
