### ISSUE TITLE
Centaur not hitting lara directly and lara teleporting under bridge 

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#857]
centaur not hitting lara and lara teleporting under the bridge after pulling a block

https://user-images.githubusercontent.com/80340234/202787417-1ecb2fb6-ca70-4f75-b763-2b8b164eccb1.mp4

**Comment by Nemoel-Tomo** [comment]
Centaur Bug fixed

**Comment by Lwmte** [comment]
Fixed another issue as well.
