### ISSUE TITLE
Pushables cant push or pull if there are pickupable items in front of pushable

### ISSUE THREAD

**Issue by goldlife2904** [MontyTRC89/TombEngine#868]
When there is a pushable and pickupable items below pushable it cannot pushed or pulled out.
![TombEditor_3oAmljAaXG](https://user-images.githubusercontent.com/75839472/203946099-53c86fa2-1277-40ab-9f71-06e21bdf047c.jpg)

TEN data for example:
https://www.dropbox.com/s/3ltsstpi5jp0nar/Jungle_Feaver.zip?dl=1

**Comment by Lwmte** [comment]
This is original bug, and it is not caused by pickups UNDER pushable, but by pickups in front of it.
