### ISSUE TITLE
SetVelocity() seems to work with vehicles only

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#889]
SetVelocity() only works with vehicles, I tested with Lara and other moveables like rollingball and they don't work.

Edit: It works when lara is in freefall, but not when she runs (ie on ground) I still don't know about other objects tho.

**Comment by Lwmte** [comment]
This is not a bug but very narrow use case for SetVelocity command. Difrrenet objects use different ways of calculating velocity (for Lara, horizontal land velocity is derived from animations, for rollingball it is derived from ItemFlags[0] and ItemFlags[1], etc etc.
