### ISSUE TITLE
Lara can pickup items hidden by Raising Block 1

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#911]
In this case Lara can pickup item that is hidden by Raising Block 1 while standing on top of it. She will do the pedestal pickup animation also.

![image](https://user-images.githubusercontent.com/120750885/208191354-804d2f64-b4d1-43db-a871-7f44e5dba3f6.png)

Compiled level here:
https://github.com/MontyTRC89/TombEngine/files/10249672/Tower.zip

**Comment by TrainWrack** [comment]
Compiled level here:
https://github.com/MontyTRC89/TombEngine/files/10249672/Tower.zip

**Comment by Lwmte** [comment]
Original issue.
