### ISSUE TITLE
Sound sourced placed in maps don't work anymore

### ISSUE THREAD

**Issue by WalrusTR** [MontyTRC89/TombEngine#919]
As title says. Apparently doesn't work any sound source.
[TenTest_NoSoundSources.zip](https://github.com/MontyTRC89/TombEngine/files/10252180/TenTest_NoSoundSources.zip)

**Comment by Kubsy** [comment]
fixed here https://github.com/MontyTRC89/Tomb-Editor/commit/5205fa1500648216752cb2e5af618c91e20f0761
