### ISSUE TITLE
SMALL_SPIDER (tr2 enemy) has pathfinding issues

### ISSUE THREAD

**Issue by motormouthmoka** [MontyTRC89/TombEngine#922]
SMALL_SPIDER does not aggressively path towards and attack Lara unless she is extremely close. Once she gets more than a few tiles away, it loses interest and will instead run around aimlessly in circles. Expected behavior is that, like almost all enemies, it will seek Lara out no matter where she is, as long as it can potentially reach her on her current elevation.

https://user-images.githubusercontent.com/47687538/208378269-deaddbc6-4f1e-4c8c-9cc1-959e54af1082.mp4

**Comment by motormouthmoka** [comment]
For comparison, this is the same enemy's behavior in 1.0.2:
https://user-images.githubusercontent.com/47687538/208384161-48230494-03ab-4760-a151-c71d214043ed.mp4

**Comment by Lwmte** [comment]
Fixed in 93d8e309c9d862232dfe8cc22d5e6092dfdc94a5
