### ISSUE TITLE
ID_BADDY1 & ID_BADD2 meshswap wrong slot

### ISSUE THREAD

**Issue by TokyoSU** [MontyTRC89/TombEngine#924]
- wrong slot for MESHSWAP3 of TR4 BADDY1
it should go to MESHSWAP_BADDY1 (1110) instead of SEARCH_OBJECT3 (419)
same for ID_MESHSWAP_BADDY2 (1111) in think

**Comment by Stranger1992** [comment]
Is ```MESHSWAP3``` used for anything else? Because I do not want to remap it and it is wrong.

**Comment by TokyoSU** [comment]
MESHSWAP1 for voncroy
MESHSWAP2 for guide/baddy2
MESHSWAP3 for baddy1

**Comment by Stranger1992** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/84292688/208771247-3200601e-dbec-49f6-b230-7d6c2da5fe0c.png">

Then I cannot remap them. This was the reason why. You'll need to do it manually and this is stated when you convert  a level in Tomb Editor to TEN.
