### ISSUE TITLE
Crash to desktop with no log on some Lua syntax errors (release build only)

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/TombEngine#936]
It's not the first time that I make the mistake of using `.` instead of `:` for calling methods.
For example, I just typed `Lara.GetState()` instead of `Lara:GetState()` in a volume function script.

With a **debug** build of TombEngine, I get something like this in the logs, and no crash:
```
[2023-Jan-01 15:57:48] [error] Could not execute function LevelFuncs.Clockwork_OnMovePushblockWatermill: Scripts\Levels\Shambala.lua:61: sol: received nil for 'self' argument (use ':' for accessing member functions, make sure member variables are preceeded by the actual object with '.' syntax)
stack traceback:
        [C]: in field 'GetState'
        Scripts\Levels\Shambala.lua:61: in function <Scripts\Levels\Shambala.lua:59>
        [C]: in ?
```

However, with a **release** build, I only get a crash to desktop, and no error appears in the log (which is why I ran the debug build in the first place).

**Comment by hispidence** [comment]
Fixed in 1.0.8. This particular error depended on a compiler flag which was not set in release mode.
